package com.gsccs.sme.plat.site.dao;

import com.gsccs.sme.plat.site.model.ContentAttachT;
import com.gsccs.sme.plat.site.model.ContentAttachTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentAttachTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_info_attach
     *
     * @mbggenerated Thu Mar 10 17:51:32 CST 2016
     */
    int countByExample(ContentAttachTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_info_attach
     *
     * @mbggenerated Thu Mar 10 17:51:32 CST 2016
     */
    int deleteByExample(ContentAttachTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_info_attach
     *
     * @mbggenerated Thu Mar 10 17:51:32 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_info_attach
     *
     * @mbggenerated Thu Mar 10 17:51:32 CST 2016
     */
    int insert(ContentAttachT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_info_attach
     *
     * @mbggenerated Thu Mar 10 17:51:32 CST 2016
     */
    int insertSelective(ContentAttachT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_info_attach
     *
     * @mbggenerated Thu Mar 10 17:51:32 CST 2016
     */
    List<ContentAttachT> selectByExample(ContentAttachTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_info_attach
     *
     * @mbggenerated Thu Mar 10 17:51:32 CST 2016
     */
    ContentAttachT selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_info_attach
     *
     * @mbggenerated Thu Mar 10 17:51:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") ContentAttachT record, @Param("example") ContentAttachTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_info_attach
     *
     * @mbggenerated Thu Mar 10 17:51:32 CST 2016
     */
    int updateByExample(@Param("record") ContentAttachT record, @Param("example") ContentAttachTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_info_attach
     *
     * @mbggenerated Thu Mar 10 17:51:32 CST 2016
     */
    int updateByPrimaryKeySelective(ContentAttachT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_info_attach
     *
     * @mbggenerated Thu Mar 10 17:51:32 CST 2016
     */
    int updateByPrimaryKey(ContentAttachT record);
}