package com.gsccs.sme.plat.auth.dao;

import com.gsccs.sme.plat.auth.model.DictGroupT;
import com.gsccs.sme.plat.auth.model.DictGroupTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictGroupTMapper {
	int countByExample(DictGroupTExample example);

	int deleteByExample(DictGroupTExample example);

	int deleteByPrimaryKey(String id);

	int insert(DictGroupT record);

	List<DictGroupT> selectByExample(DictGroupTExample example);

	DictGroupT selectByPrimaryKey(String id);

	int updateByExampleSelective(@Param("record") DictGroupT record,
			@Param("example") DictGroupTExample example);

	int updateByExample(@Param("record") DictGroupT record,
			@Param("example") DictGroupTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table plat_dict_group
	 * 
	 * @mbggenerated Wed Mar 09 16:36:37 CST 2016
	 */
	int updateByPrimaryKeySelective(DictGroupT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table plat_dict_group
	 * 
	 * @mbggenerated Wed Mar 09 16:36:37 CST 2016
	 */
	int updateByPrimaryKey(DictGroupT record);

	DictGroupT selectByTitle(String title);

	DictGroupT selectByCode(String code);
}