package com.gsccs.sme.plat.svg.dao;

import com.gsccs.sme.plat.svg.model.ParkT;
import com.gsccs.sme.plat.svg.model.ParkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ParkMapper {

	int countByExample(ParkExample example);

	int deleteByExample(ParkExample example);

	int deleteByPrimaryKey(Long id);

	int insert(ParkT record);

	int insertSelective(ParkT record);

	List<ParkT> selectPageByExample(ParkExample example);
	//List<ParkT> selectByExample(ParkExample example);

	ParkT selectByPrimaryKey(Long id);

	int updateByExampleSelective(@Param("record") ParkT record,
			@Param("example") ParkExample example);

	int updateByExampleWithBLOBs(@Param("record") ParkT record,
			@Param("example") ParkExample example);

	int updateByExample(@Param("record") ParkT record,
			@Param("example") ParkExample example);

	int updateByPrimaryKeySelective(ParkT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sme_indust_park
	 * 
	 * @mbggenerated Sat Apr 30 17:40:32 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(ParkT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sme_indust_park
	 * 
	 * @mbggenerated Sat Apr 30 17:40:32 CST 2016
	 */
	int updateByPrimaryKey(ParkT record);
}