package com.gsccs.sme.plat.svg.dao;

import com.gsccs.sme.plat.svg.model.RegTypeT;
import com.gsccs.sme.plat.svg.model.RegTypeTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegTypeTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_type
     *
     * @mbggenerated Thu Mar 03 21:03:31 CST 2016
     */
    int countByExample(RegTypeTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_type
     *
     * @mbggenerated Thu Mar 03 21:03:31 CST 2016
     */
    int deleteByExample(RegTypeTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_type
     *
     * @mbggenerated Thu Mar 03 21:03:31 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_type
     *
     * @mbggenerated Thu Mar 03 21:03:31 CST 2016
     */
    int insert(RegTypeT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_type
     *
     * @mbggenerated Thu Mar 03 21:03:31 CST 2016
     */
    int insertSelective(RegTypeT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_type
     *
     * @mbggenerated Thu Mar 03 21:03:31 CST 2016
     */
    List<RegTypeT> selectByExample(RegTypeTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_type
     *
     * @mbggenerated Thu Mar 03 21:03:31 CST 2016
     */
    RegTypeT selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_type
     *
     * @mbggenerated Thu Mar 03 21:03:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") RegTypeT record, @Param("example") RegTypeTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_type
     *
     * @mbggenerated Thu Mar 03 21:03:31 CST 2016
     */
    int updateByExample(@Param("record") RegTypeT record, @Param("example") RegTypeTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_type
     *
     * @mbggenerated Thu Mar 03 21:03:31 CST 2016
     */
    int updateByPrimaryKeySelective(RegTypeT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_type
     *
     * @mbggenerated Thu Mar 03 21:03:31 CST 2016
     */
    int updateByPrimaryKey(RegTypeT record);
}