package com.gsccs.sme.plat.task.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.gsccs.sme.api.domain.CapitalReply;
import com.gsccs.sme.plat.task.model.CapitalReplyExample;

public interface CapitalReplyMapper {
    
    int countByExample(CapitalReplyExample example);
    int deleteByExample(CapitalReplyExample example);
    int deleteByPrimaryKey(Long id);
    int insert(CapitalReply record);
    int insertSelective(CapitalReply record);
    
    List<CapitalReply> selectApplByExample(CapitalReplyExample example);
    List<CapitalReply> selectAllByExample(CapitalReplyExample example);
    CapitalReply selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") CapitalReply record, @Param("example") CapitalReplyExample example);
    int updateByExample(@Param("record") CapitalReply record, @Param("example") CapitalReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_capital_reply
     *
     * @mbggenerated Sat Jul 16 21:18:37 CST 2016
     */
    int updateByPrimaryKeySelective(CapitalReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_capital_reply
     *
     * @mbggenerated Sat Jul 16 21:18:37 CST 2016
     */
    int updateByPrimaryKey(CapitalReply record);
}