package com.gsccs.sme.plat.task.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.gsccs.sme.api.domain.CooperFlow;
import com.gsccs.sme.plat.task.model.CooperFlowExample;

public interface CooperFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_cooperflow
     *
     * @mbggenerated Sat Jul 16 17:04:25 CST 2016
     */
    int countByExample(CooperFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_cooperflow
     *
     * @mbggenerated Sat Jul 16 17:04:25 CST 2016
     */
    int deleteByExample(CooperFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_cooperflow
     *
     * @mbggenerated Sat Jul 16 17:04:25 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_cooperflow
     *
     * @mbggenerated Sat Jul 16 17:04:25 CST 2016
     */
    int insert(CooperFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_cooperflow
     *
     * @mbggenerated Sat Jul 16 17:04:25 CST 2016
     */
    int insertSelective(CooperFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_cooperflow
     *
     * @mbggenerated Sat Jul 16 17:04:25 CST 2016
     */
    List<CooperFlow> selectByExample(CooperFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_cooperflow
     *
     * @mbggenerated Sat Jul 16 17:04:25 CST 2016
     */
    CooperFlow selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_cooperflow
     *
     * @mbggenerated Sat Jul 16 17:04:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") CooperFlow record, @Param("example") CooperFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_cooperflow
     *
     * @mbggenerated Sat Jul 16 17:04:25 CST 2016
     */
    int updateByExample(@Param("record") CooperFlow record, @Param("example") CooperFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_cooperflow
     *
     * @mbggenerated Sat Jul 16 17:04:25 CST 2016
     */
    int updateByPrimaryKeySelective(CooperFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_cooperflow
     *
     * @mbggenerated Sat Jul 16 17:04:25 CST 2016
     */
    int updateByPrimaryKey(CooperFlow record);
}