package com.gsccs.sme.plat.rtable.dao;

import com.gsccs.sme.plat.rtable.model.ReportAttachT;
import com.gsccs.sme.plat.rtable.model.ReportAttachTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReportAttachTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_report_attach
     *
     * @mbggenerated Thu Apr 14 22:53:07 CST 2016
     */
    int countByExample(ReportAttachTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_report_attach
     *
     * @mbggenerated Thu Apr 14 22:53:07 CST 2016
     */
    int deleteByExample(ReportAttachTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_report_attach
     *
     * @mbggenerated Thu Apr 14 22:53:07 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_report_attach
     *
     * @mbggenerated Thu Apr 14 22:53:07 CST 2016
     */
    int insert(ReportAttachT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_report_attach
     *
     * @mbggenerated Thu Apr 14 22:53:07 CST 2016
     */
    int insertSelective(ReportAttachT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_report_attach
     *
     * @mbggenerated Thu Apr 14 22:53:07 CST 2016
     */
    List<ReportAttachT> selectByExample(ReportAttachTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_report_attach
     *
     * @mbggenerated Thu Apr 14 22:53:07 CST 2016
     */
    ReportAttachT selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_report_attach
     *
     * @mbggenerated Thu Apr 14 22:53:07 CST 2016
     */
    int updateByExampleSelective(@Param("record") ReportAttachT record, @Param("example") ReportAttachTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_report_attach
     *
     * @mbggenerated Thu Apr 14 22:53:07 CST 2016
     */
    int updateByExample(@Param("record") ReportAttachT record, @Param("example") ReportAttachTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_report_attach
     *
     * @mbggenerated Thu Apr 14 22:53:07 CST 2016
     */
    int updateByPrimaryKeySelective(ReportAttachT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_report_attach
     *
     * @mbggenerated Thu Apr 14 22:53:07 CST 2016
     */
    int updateByPrimaryKey(ReportAttachT record);
}