package com.gsccs.sme.plat.auth.model;

public class DictGroupT {
    
    private String id;
    private String code;
    private String title;
    private String val;
    private String remark;
    private String status;
    
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_dict_group.id
     *
     * @param id the value for plat_dict_group.id
     *
     * @mbggenerated Wed Mar 09 16:36:37 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_dict_group.code
     *
     * @return the value of plat_dict_group.code
     *
     * @mbggenerated Wed Mar 09 16:36:37 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_dict_group.code
     *
     * @param code the value for plat_dict_group.code
     *
     * @mbggenerated Wed Mar 09 16:36:37 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_dict_group.title
     *
     * @return the value of plat_dict_group.title
     *
     * @mbggenerated Wed Mar 09 16:36:37 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_dict_group.title
     *
     * @param title the value for plat_dict_group.title
     *
     * @mbggenerated Wed Mar 09 16:36:37 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_dict_group.val
     *
     * @return the value of plat_dict_group.val
     *
     * @mbggenerated Wed Mar 09 16:36:37 CST 2016
     */
    public String getVal() {
        return val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_dict_group.val
     *
     * @param val the value for plat_dict_group.val
     *
     * @mbggenerated Wed Mar 09 16:36:37 CST 2016
     */
    public void setVal(String val) {
        this.val = val == null ? null : val.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_dict_group.remark
     *
     * @return the value of plat_dict_group.remark
     *
     * @mbggenerated Wed Mar 09 16:36:37 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_dict_group.remark
     *
     * @param remark the value for plat_dict_group.remark
     *
     * @mbggenerated Wed Mar 09 16:36:37 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_dict_group.status
     *
     * @return the value of plat_dict_group.status
     *
     * @mbggenerated Wed Mar 09 16:36:37 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_dict_group.status
     *
     * @param status the value for plat_dict_group.status
     *
     * @mbggenerated Wed Mar 09 16:36:37 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}