package com.gsccs.sme.plat.svg.model;

public class AppealAttachT {
   
    private Long id;
    private Long topicid;
    private Long itemid;
    private Long corpid;
    private String filename;
    private String filepath;
    private String filetype;

    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sme_appeal_attach.id
     *
     * @param id the value for sme_appeal_attach.id
     *
     * @mbggenerated Sun Mar 20 15:44:10 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sme_appeal_attach.topicid
     *
     * @return the value of sme_appeal_attach.topicid
     *
     * @mbggenerated Sun Mar 20 15:44:10 CST 2016
     */
    public Long getTopicid() {
        return topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sme_appeal_attach.topicid
     *
     * @param topicid the value for sme_appeal_attach.topicid
     *
     * @mbggenerated Sun Mar 20 15:44:10 CST 2016
     */
    public void setTopicid(Long topicid) {
        this.topicid = topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sme_appeal_attach.itemid
     *
     * @return the value of sme_appeal_attach.itemid
     *
     * @mbggenerated Sun Mar 20 15:44:10 CST 2016
     */
    public Long getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sme_appeal_attach.itemid
     *
     * @param itemid the value for sme_appeal_attach.itemid
     *
     * @mbggenerated Sun Mar 20 15:44:10 CST 2016
     */
    public void setItemid(Long itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sme_appeal_attach.corpid
     *
     * @return the value of sme_appeal_attach.corpid
     *
     * @mbggenerated Sun Mar 20 15:44:10 CST 2016
     */
    public Long getCorpid() {
        return corpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sme_appeal_attach.corpid
     *
     * @param corpid the value for sme_appeal_attach.corpid
     *
     * @mbggenerated Sun Mar 20 15:44:10 CST 2016
     */
    public void setCorpid(Long corpid) {
        this.corpid = corpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sme_appeal_attach.filename
     *
     * @return the value of sme_appeal_attach.filename
     *
     * @mbggenerated Sun Mar 20 15:44:10 CST 2016
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sme_appeal_attach.filename
     *
     * @param filename the value for sme_appeal_attach.filename
     *
     * @mbggenerated Sun Mar 20 15:44:10 CST 2016
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sme_appeal_attach.filepath
     *
     * @return the value of sme_appeal_attach.filepath
     *
     * @mbggenerated Sun Mar 20 15:44:10 CST 2016
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sme_appeal_attach.filepath
     *
     * @param filepath the value for sme_appeal_attach.filepath
     *
     * @mbggenerated Sun Mar 20 15:44:10 CST 2016
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sme_appeal_attach.filetype
     *
     * @return the value of sme_appeal_attach.filetype
     *
     * @mbggenerated Sun Mar 20 15:44:10 CST 2016
     */
    public String getFiletype() {
        return filetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sme_appeal_attach.filetype
     *
     * @param filetype the value for sme_appeal_attach.filetype
     *
     * @mbggenerated Sun Mar 20 15:44:10 CST 2016
     */
    public void setFiletype(String filetype) {
        this.filetype = filetype == null ? null : filetype.trim();
    }
}