package com.gsccs.sme.plat.svg.model;

import java.util.ArrayList;
import java.util.List;

import com.gsccs.sme.plat.bass.BaseExample;

public class ExpertTExample extends BaseExample {

	protected String orderByClause;
	protected boolean distinct;

	protected List<Criteria> oredCriteria;

	public ExpertTExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	public String getOrderByClause() {
		return orderByClause;
	}

	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sme_expert
	 * 
	 * @mbggenerated Fri Feb 26 17:35:32 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sme_expert
	 * 
	 * @mbggenerated Fri Feb 26 17:35:32 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sme_expert
	 * 
	 * @mbggenerated Fri Feb 26 17:35:32 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sme_expert
	 * 
	 * @mbggenerated Fri Feb 26 17:35:32 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sme_expert
	 * 
	 * @mbggenerated Fri Feb 26 17:35:32 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sme_expert
	 * 
	 * @mbggenerated Fri Feb 26 17:35:32 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sme_expert
	 * 
	 * @mbggenerated Fri Feb 26 17:35:32 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table sme_expert
	 * 
	 * @mbggenerated Fri Feb 26 17:35:32 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andLogoIsNull() {
			addCriterion("logo is null");
			return (Criteria) this;
		}

		public Criteria andLogoIsNotNull() {
			addCriterion("logo is not null");
			return (Criteria) this;
		}

		public Criteria andLogoEqualTo(String value) {
			addCriterion("logo =", value, "logo");
			return (Criteria) this;
		}

		public Criteria andDegreeIsNull() {
			addCriterion("degree is null");
			return (Criteria) this;
		}

		public Criteria andDegreeIsNotNull() {
			addCriterion("degree is not null");
			return (Criteria) this;
		}

		public Criteria andDegreeEqualTo(String value) {
			addCriterion("degree =", value, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeNotEqualTo(String value) {
			addCriterion("degree <>", value, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeGreaterThan(String value) {
			addCriterion("degree >", value, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeGreaterThanOrEqualTo(String value) {
			addCriterion("degree >=", value, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeLessThan(String value) {
			addCriterion("degree <", value, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeLessThanOrEqualTo(String value) {
			addCriterion("degree <=", value, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeLike(String value) {
			addCriterion("degree like", value, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeNotLike(String value) {
			addCriterion("degree not like", value, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeIn(List<String> values) {
			addCriterion("degree in", values, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeNotIn(List<String> values) {
			addCriterion("degree not in", values, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeBetween(String value1, String value2) {
			addCriterion("degree between", value1, value2, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeNotBetween(String value1, String value2) {
			addCriterion("degree not between", value1, value2, "degree");
			return (Criteria) this;
		}

		public Criteria andClassidIsNull() {
			addCriterion("classid is null");
			return (Criteria) this;
		}

		public Criteria andClassidIsNotNull() {
			addCriterion("classid is not null");
			return (Criteria) this;
		}

		public Criteria andClassidEqualTo(String value) {
			addCriterion("classid =", value, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidNotEqualTo(String value) {
			addCriterion("classid <>", value, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidGreaterThan(String value) {
			addCriterion("classid >", value, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidGreaterThanOrEqualTo(String value) {
			addCriterion("classid >=", value, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidLessThan(String value) {
			addCriterion("classid <", value, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidLessThanOrEqualTo(String value) {
			addCriterion("classid <=", value, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidLike(String value) {
			addCriterion("classid like", value, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidNotLike(String value) {
			addCriterion("classid not like", value, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidIn(List<String> values) {
			addCriterion("classid in", values, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidNotIn(List<String> values) {
			addCriterion("classid not in", values, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidBetween(String value1, String value2) {
			addCriterion("classid between", value1, value2, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidNotBetween(String value1, String value2) {
			addCriterion("classid not between", value1, value2, "classid");
			return (Criteria) this;
		}

		public Criteria andTechnicalIsNull() {
			addCriterion("technical is null");
			return (Criteria) this;
		}

		public Criteria andTechnicalIsNotNull() {
			addCriterion("technical is not null");
			return (Criteria) this;
		}

		public Criteria andTechnicalEqualTo(String value) {
			addCriterion("technical =", value, "technical");
			return (Criteria) this;
		}

		public Criteria andTechnicalNotEqualTo(String value) {
			addCriterion("technical <>", value, "technical");
			return (Criteria) this;
		}

		public Criteria andTechnicalGreaterThan(String value) {
			addCriterion("technical >", value, "technical");
			return (Criteria) this;
		}

		public Criteria andTechnicalGreaterThanOrEqualTo(String value) {
			addCriterion("technical >=", value, "technical");
			return (Criteria) this;
		}

		public Criteria andTechnicalLessThan(String value) {
			addCriterion("technical <", value, "technical");
			return (Criteria) this;
		}

		public Criteria andTechnicalLessThanOrEqualTo(String value) {
			addCriterion("technical <=", value, "technical");
			return (Criteria) this;
		}

		public Criteria andTechnicalLike(String value) {
			addCriterion("technical like", value, "technical");
			return (Criteria) this;
		}

		public Criteria andTechnicalNotLike(String value) {
			addCriterion("technical not like", value, "technical");
			return (Criteria) this;
		}

		public Criteria andTechnicalIn(List<String> values) {
			addCriterion("technical in", values, "technical");
			return (Criteria) this;
		}

		public Criteria andTechnicalNotIn(List<String> values) {
			addCriterion("technical not in", values, "technical");
			return (Criteria) this;
		}

		public Criteria andTechnicalBetween(String value1, String value2) {
			addCriterion("technical between", value1, value2, "technical");
			return (Criteria) this;
		}

		public Criteria andTechnicalNotBetween(String value1, String value2) {
			addCriterion("technical not between", value1, value2, "technical");
			return (Criteria) this;
		}

		public Criteria andProflifeIsNull() {
			addCriterion("proflife is null");
			return (Criteria) this;
		}

		public Criteria andProflifeIsNotNull() {
			addCriterion("proflife is not null");
			return (Criteria) this;
		}

		public Criteria andProflifeEqualTo(Integer value) {
			addCriterion("proflife =", value, "proflife");
			return (Criteria) this;
		}

		public Criteria andProflifeNotEqualTo(Integer value) {
			addCriterion("proflife <>", value, "proflife");
			return (Criteria) this;
		}

		public Criteria andProflifeGreaterThan(Integer value) {
			addCriterion("proflife >", value, "proflife");
			return (Criteria) this;
		}

		public Criteria andProflifeGreaterThanOrEqualTo(Integer value) {
			addCriterion("proflife >=", value, "proflife");
			return (Criteria) this;
		}

		public Criteria andProflifeLessThan(Integer value) {
			addCriterion("proflife <", value, "proflife");
			return (Criteria) this;
		}

		public Criteria andProflifeLessThanOrEqualTo(Integer value) {
			addCriterion("proflife <=", value, "proflife");
			return (Criteria) this;
		}

		public Criteria andProflifeIn(List<Integer> values) {
			addCriterion("proflife in", values, "proflife");
			return (Criteria) this;
		}

		public Criteria andProflifeNotIn(List<Integer> values) {
			addCriterion("proflife not in", values, "proflife");
			return (Criteria) this;
		}

		public Criteria andProflifeBetween(Integer value1, Integer value2) {
			addCriterion("proflife between", value1, value2, "proflife");
			return (Criteria) this;
		}

		public Criteria andProflifeNotBetween(Integer value1, Integer value2) {
			addCriterion("proflife not between", value1, value2, "proflife");
			return (Criteria) this;
		}

		public Criteria andSucaseIsNull() {
			addCriterion("sucase is null");
			return (Criteria) this;
		}

		public Criteria andSucaseIsNotNull() {
			addCriterion("sucase is not null");
			return (Criteria) this;
		}

		public Criteria andSucaseEqualTo(String value) {
			addCriterion("sucase =", value, "sucase");
			return (Criteria) this;
		}

		public Criteria andSucaseNotEqualTo(String value) {
			addCriterion("sucase <>", value, "sucase");
			return (Criteria) this;
		}

		public Criteria andSucaseGreaterThan(String value) {
			addCriterion("sucase >", value, "sucase");
			return (Criteria) this;
		}

		public Criteria andSucaseGreaterThanOrEqualTo(String value) {
			addCriterion("sucase >=", value, "sucase");
			return (Criteria) this;
		}

		public Criteria andSucaseLessThan(String value) {
			addCriterion("sucase <", value, "sucase");
			return (Criteria) this;
		}

		public Criteria andSucaseLessThanOrEqualTo(String value) {
			addCriterion("sucase <=", value, "sucase");
			return (Criteria) this;
		}

		public Criteria andSucaseLike(String value) {
			addCriterion("sucase like", value, "sucase");
			return (Criteria) this;
		}

		public Criteria andSucaseNotLike(String value) {
			addCriterion("sucase not like", value, "sucase");
			return (Criteria) this;
		}

		public Criteria andSucaseIn(List<String> values) {
			addCriterion("sucase in", values, "sucase");
			return (Criteria) this;
		}

		public Criteria andSucaseNotIn(List<String> values) {
			addCriterion("sucase not in", values, "sucase");
			return (Criteria) this;
		}

		public Criteria andSucaseBetween(String value1, String value2) {
			addCriterion("sucase between", value1, value2, "sucase");
			return (Criteria) this;
		}

		public Criteria andSucaseNotBetween(String value1, String value2) {
			addCriterion("sucase not between", value1, value2, "sucase");
			return (Criteria) this;
		}

		public Criteria andContentIsNull() {
			addCriterion("content is null");
			return (Criteria) this;
		}

		public Criteria andContentIsNotNull() {
			addCriterion("content is not null");
			return (Criteria) this;
		}

		public Criteria andContentEqualTo(String value) {
			addCriterion("content =", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotEqualTo(String value) {
			addCriterion("content <>", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThan(String value) {
			addCriterion("content >", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThanOrEqualTo(String value) {
			addCriterion("content >=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThan(String value) {
			addCriterion("content <", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThanOrEqualTo(String value) {
			addCriterion("content <=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLike(String value) {
			addCriterion("content like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotLike(String value) {
			addCriterion("content not like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentIn(List<String> values) {
			addCriterion("content in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotIn(List<String> values) {
			addCriterion("content not in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentBetween(String value1, String value2) {
			addCriterion("content between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotBetween(String value1, String value2) {
			addCriterion("content not between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("phone is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("phone is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("phone =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("phone <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("phone >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("phone >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("phone <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("phone <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("phone like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("phone not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("phone in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("phone not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("phone between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("phone not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andTelnumIsNull() {
			addCriterion("telnum is null");
			return (Criteria) this;
		}

		public Criteria andTelnumIsNotNull() {
			addCriterion("telnum is not null");
			return (Criteria) this;
		}

		public Criteria andTelnumEqualTo(String value) {
			addCriterion("telnum =", value, "telnum");
			return (Criteria) this;
		}

		public Criteria andTelnumNotEqualTo(String value) {
			addCriterion("telnum <>", value, "telnum");
			return (Criteria) this;
		}

		public Criteria andTelnumGreaterThan(String value) {
			addCriterion("telnum >", value, "telnum");
			return (Criteria) this;
		}

		public Criteria andTelnumGreaterThanOrEqualTo(String value) {
			addCriterion("telnum >=", value, "telnum");
			return (Criteria) this;
		}

		public Criteria andTelnumLessThan(String value) {
			addCriterion("telnum <", value, "telnum");
			return (Criteria) this;
		}

		public Criteria andTelnumLessThanOrEqualTo(String value) {
			addCriterion("telnum <=", value, "telnum");
			return (Criteria) this;
		}

		public Criteria andTelnumLike(String value) {
			addCriterion("telnum like", value, "telnum");
			return (Criteria) this;
		}

		public Criteria andTelnumNotLike(String value) {
			addCriterion("telnum not like", value, "telnum");
			return (Criteria) this;
		}

		public Criteria andTelnumIn(List<String> values) {
			addCriterion("telnum in", values, "telnum");
			return (Criteria) this;
		}

		public Criteria andTelnumNotIn(List<String> values) {
			addCriterion("telnum not in", values, "telnum");
			return (Criteria) this;
		}

		public Criteria andTelnumBetween(String value1, String value2) {
			addCriterion("telnum between", value1, value2, "telnum");
			return (Criteria) this;
		}

		public Criteria andTelnumNotBetween(String value1, String value2) {
			addCriterion("telnum not between", value1, value2, "telnum");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andAgeIsNull() {
			addCriterion("age is null");
			return (Criteria) this;
		}

		public Criteria andAgeIsNotNull() {
			addCriterion("age is not null");
			return (Criteria) this;
		}

		public Criteria andAgeEqualTo(Integer value) {
			addCriterion("age =", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotEqualTo(Integer value) {
			addCriterion("age <>", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeGreaterThan(Integer value) {
			addCriterion("age >", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
			addCriterion("age >=", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeLessThan(Integer value) {
			addCriterion("age <", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeLessThanOrEqualTo(Integer value) {
			addCriterion("age <=", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeIn(List<Integer> values) {
			addCriterion("age in", values, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotIn(List<Integer> values) {
			addCriterion("age not in", values, "age");
			return (Criteria) this;
		}

		public Criteria andAgeBetween(Integer value1, Integer value2) {
			addCriterion("age between", value1, value2, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotBetween(Integer value1, Integer value2) {
			addCriterion("age not between", value1, value2, "age");
			return (Criteria) this;
		}

		public Criteria andSexIsNull() {
			addCriterion("sex is null");
			return (Criteria) this;
		}

		public Criteria andSexIsNotNull() {
			addCriterion("sex is not null");
			return (Criteria) this;
		}

		public Criteria andSexEqualTo(String value) {
			addCriterion("sex =", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotEqualTo(String value) {
			addCriterion("sex <>", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThan(String value) {
			addCriterion("sex >", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThanOrEqualTo(String value) {
			addCriterion("sex >=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThan(String value) {
			addCriterion("sex <", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThanOrEqualTo(String value) {
			addCriterion("sex <=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLike(String value) {
			addCriterion("sex like", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotLike(String value) {
			addCriterion("sex not like", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexIn(List<String> values) {
			addCriterion("sex in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotIn(List<String> values) {
			addCriterion("sex not in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexBetween(String value1, String value2) {
			addCriterion("sex between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotBetween(String value1, String value2) {
			addCriterion("sex not between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andDutiesIsNull() {
			addCriterion("duties is null");
			return (Criteria) this;
		}

		public Criteria andDutiesIsNotNull() {
			addCriterion("duties is not null");
			return (Criteria) this;
		}

		public Criteria andDutiesEqualTo(String value) {
			addCriterion("duties =", value, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesNotEqualTo(String value) {
			addCriterion("duties <>", value, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesGreaterThan(String value) {
			addCriterion("duties >", value, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesGreaterThanOrEqualTo(String value) {
			addCriterion("duties >=", value, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesLessThan(String value) {
			addCriterion("duties <", value, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesLessThanOrEqualTo(String value) {
			addCriterion("duties <=", value, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesLike(String value) {
			addCriterion("duties like", value, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesNotLike(String value) {
			addCriterion("duties not like", value, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesIn(List<String> values) {
			addCriterion("duties in", values, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesNotIn(List<String> values) {
			addCriterion("duties not in", values, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesBetween(String value1, String value2) {
			addCriterion("duties between", value1, value2, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesNotBetween(String value1, String value2) {
			addCriterion("duties not between", value1, value2, "duties");
			return (Criteria) this;
		}

		public Criteria andStateIsNull() {
			addCriterion("state is null");
			return (Criteria) this;
		}

		public Criteria andStateIsNotNull() {
			addCriterion("state is not null");
			return (Criteria) this;
		}

		public Criteria andStateEqualTo(String value) {
			addCriterion("state =", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotEqualTo(String value) {
			addCriterion("state <>", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThan(String value) {
			addCriterion("state >", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThanOrEqualTo(String value) {
			addCriterion("state >=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThan(String value) {
			addCriterion("state <", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThanOrEqualTo(String value) {
			addCriterion("state <=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLike(String value) {
			addCriterion("state like", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotLike(String value) {
			addCriterion("state not like", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateIn(List<String> values) {
			addCriterion("state in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotIn(List<String> values) {
			addCriterion("state not in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateBetween(String value1, String value2) {
			addCriterion("state between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotBetween(String value1, String value2) {
			addCriterion("state not between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andSalenumIsNull() {
			addCriterion("salenum is null");
			return (Criteria) this;
		}

		public Criteria andSalenumIsNotNull() {
			addCriterion("salenum is not null");
			return (Criteria) this;
		}

		public Criteria andSalenumEqualTo(Integer value) {
			addCriterion("salenum =", value, "salenum");
			return (Criteria) this;
		}

		public Criteria andSalenumNotEqualTo(Integer value) {
			addCriterion("salenum <>", value, "salenum");
			return (Criteria) this;
		}

		public Criteria andSalenumGreaterThan(Integer value) {
			addCriterion("salenum >", value, "salenum");
			return (Criteria) this;
		}

		public Criteria andSalenumGreaterThanOrEqualTo(Integer value) {
			addCriterion("salenum >=", value, "salenum");
			return (Criteria) this;
		}

		public Criteria andSalenumLessThan(Integer value) {
			addCriterion("salenum <", value, "salenum");
			return (Criteria) this;
		}

		public Criteria andSalenumLessThanOrEqualTo(Integer value) {
			addCriterion("salenum <=", value, "salenum");
			return (Criteria) this;
		}

		public Criteria andSalenumIn(List<Integer> values) {
			addCriterion("salenum in", values, "salenum");
			return (Criteria) this;
		}

		public Criteria andSalenumNotIn(List<Integer> values) {
			addCriterion("salenum not in", values, "salenum");
			return (Criteria) this;
		}

		public Criteria andSalenumBetween(Integer value1, Integer value2) {
			addCriterion("salenum between", value1, value2, "salenum");
			return (Criteria) this;
		}

		public Criteria andSalenumNotBetween(Integer value1, Integer value2) {
			addCriterion("salenum not between", value1, value2, "salenum");
			return (Criteria) this;
		}

		public Criteria andClicknumIsNull() {
			addCriterion("clicknum is null");
			return (Criteria) this;
		}

		public Criteria andClicknumIsNotNull() {
			addCriterion("clicknum is not null");
			return (Criteria) this;
		}

		public Criteria andClicknumEqualTo(Integer value) {
			addCriterion("clicknum =", value, "clicknum");
			return (Criteria) this;
		}

		public Criteria andClicknumNotEqualTo(Integer value) {
			addCriterion("clicknum <>", value, "clicknum");
			return (Criteria) this;
		}

		public Criteria andClicknumGreaterThan(Integer value) {
			addCriterion("clicknum >", value, "clicknum");
			return (Criteria) this;
		}

		public Criteria andClicknumGreaterThanOrEqualTo(Integer value) {
			addCriterion("clicknum >=", value, "clicknum");
			return (Criteria) this;
		}

		public Criteria andClicknumLessThan(Integer value) {
			addCriterion("clicknum <", value, "clicknum");
			return (Criteria) this;
		}

		public Criteria andClicknumLessThanOrEqualTo(Integer value) {
			addCriterion("clicknum <=", value, "clicknum");
			return (Criteria) this;
		}

		public Criteria andClicknumIn(List<Integer> values) {
			addCriterion("clicknum in", values, "clicknum");
			return (Criteria) this;
		}

		public Criteria andClicknumNotIn(List<Integer> values) {
			addCriterion("clicknum not in", values, "clicknum");
			return (Criteria) this;
		}

		public Criteria andClicknumBetween(Integer value1, Integer value2) {
			addCriterion("clicknum between", value1, value2, "clicknum");
			return (Criteria) this;
		}

		public Criteria andClicknumNotBetween(Integer value1, Integer value2) {
			addCriterion("clicknum not between", value1, value2, "clicknum");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table sme_expert
	 * 
	 * @mbggenerated do_not_delete_during_merge Fri Feb 26 17:35:32 CST 2016
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table sme_expert
	 * 
	 * @mbggenerated Fri Feb 26 17:35:32 CST 2016
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}