package com.gsccs.sme.plat.svg.model;

public class IndustryT {

	private Long id;
	private Long parid;
	private String title;
	private String code;
	private String state;
	private Integer clicknum;
	private String pagemark;
	private Integer indexnum;

	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sme_industry.id
	 * 
	 * @param id
	 *            the value for sme_industry.id
	 * 
	 * @mbggenerated Thu Mar 03 21:25:32 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sme_industry.parid
	 * 
	 * @return the value of sme_industry.parid
	 * 
	 * @mbggenerated Thu Mar 03 21:25:32 CST 2016
	 */
	public Long getParid() {
		return parid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sme_industry.parid
	 * 
	 * @param parid
	 *            the value for sme_industry.parid
	 * 
	 * @mbggenerated Thu Mar 03 21:25:32 CST 2016
	 */
	public void setParid(Long parid) {
		this.parid = parid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sme_industry.title
	 * 
	 * @return the value of sme_industry.title
	 * 
	 * @mbggenerated Thu Mar 03 21:25:32 CST 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sme_industry.title
	 * 
	 * @param title
	 *            the value for sme_industry.title
	 * 
	 * @mbggenerated Thu Mar 03 21:25:32 CST 2016
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sme_industry.code
	 * 
	 * @return the value of sme_industry.code
	 * 
	 * @mbggenerated Thu Mar 03 21:25:32 CST 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sme_industry.code
	 * 
	 * @param code
	 *            the value for sme_industry.code
	 * 
	 * @mbggenerated Thu Mar 03 21:25:32 CST 2016
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sme_industry.state
	 * 
	 * @return the value of sme_industry.state
	 * 
	 * @mbggenerated Thu Mar 03 21:25:32 CST 2016
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sme_industry.state
	 * 
	 * @param state
	 *            the value for sme_industry.state
	 * 
	 * @mbggenerated Thu Mar 03 21:25:32 CST 2016
	 */
	public void setState(String state) {
		this.state = state == null ? null : state.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sme_industry.clicknum
	 * 
	 * @return the value of sme_industry.clicknum
	 * 
	 * @mbggenerated Thu Mar 03 21:25:32 CST 2016
	 */
	public Integer getClicknum() {
		return clicknum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sme_industry.clicknum
	 * 
	 * @param clicknum
	 *            the value for sme_industry.clicknum
	 * 
	 * @mbggenerated Thu Mar 03 21:25:32 CST 2016
	 */
	public void setClicknum(Integer clicknum) {
		this.clicknum = clicknum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sme_industry.pagemark
	 * 
	 * @return the value of sme_industry.pagemark
	 * 
	 * @mbggenerated Thu Mar 03 21:25:32 CST 2016
	 */
	public String getPagemark() {
		return pagemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sme_industry.pagemark
	 * 
	 * @param pagemark
	 *            the value for sme_industry.pagemark
	 * 
	 * @mbggenerated Thu Mar 03 21:25:32 CST 2016
	 */
	public void setPagemark(String pagemark) {
		this.pagemark = pagemark == null ? null : pagemark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sme_industry.indexnum
	 * 
	 * @return the value of sme_industry.indexnum
	 * 
	 * @mbggenerated Thu Mar 03 21:25:32 CST 2016
	 */
	public Integer getIndexnum() {
		return indexnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sme_industry.indexnum
	 * 
	 * @param indexnum
	 *            the value for sme_industry.indexnum
	 * 
	 * @mbggenerated Thu Mar 03 21:25:32 CST 2016
	 */
	public void setIndexnum(Integer indexnum) {
		this.indexnum = indexnum;
	}
}