package com.gsccs.sme.plat.svg.model;


/**
 * 商家支付方式配置类
 * @author x.d zhang
 *
 */
public class SellerPay {
    
    private String id;
    private String storeId;
    private String appId;
    private String appKey;
    private String signType;
    private String sellerId;
    private String sellerEmail;
    private String payType;
    private String service;
    private String status;

    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_pay_store.id
     *
     * @param id the value for plat_pay_store.id
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_pay_store.store_id
     *
     * @return the value of plat_pay_store.store_id
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_pay_store.store_id
     *
     * @param storeId the value for plat_pay_store.store_id
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_pay_store.app_id
     *
     * @return the value of plat_pay_store.app_id
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_pay_store.app_id
     *
     * @param appId the value for plat_pay_store.app_id
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_pay_store.app_key
     *
     * @return the value of plat_pay_store.app_key
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_pay_store.app_key
     *
     * @param appKey the value for plat_pay_store.app_key
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_pay_store.sign_type
     *
     * @return the value of plat_pay_store.sign_type
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    public String getSignType() {
        return signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_pay_store.sign_type
     *
     * @param signType the value for plat_pay_store.sign_type
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    public void setSignType(String signType) {
        this.signType = signType == null ? null : signType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_pay_store.seller_id
     *
     * @return the value of plat_pay_store.seller_id
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_pay_store.seller_id
     *
     * @param sellerId the value for plat_pay_store.seller_id
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId == null ? null : sellerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_pay_store.seller_email
     *
     * @return the value of plat_pay_store.seller_email
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    public String getSellerEmail() {
        return sellerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_pay_store.seller_email
     *
     * @param sellerEmail the value for plat_pay_store.seller_email
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    public void setSellerEmail(String sellerEmail) {
        this.sellerEmail = sellerEmail == null ? null : sellerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_pay_store.pay_type
     *
     * @return the value of plat_pay_store.pay_type
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_pay_store.pay_type
     *
     * @param payType the value for plat_pay_store.pay_type
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_pay_store.service
     *
     * @return the value of plat_pay_store.service
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    public String getService() {
        return service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_pay_store.service
     *
     * @param service the value for plat_pay_store.service
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    public void setService(String service) {
        this.service = service == null ? null : service.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_pay_store.status
     *
     * @return the value of plat_pay_store.status
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_pay_store.status
     *
     * @param status the value for plat_pay_store.status
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}