package com.gsccs.sme.plat.svg.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.gsccs.sme.plat.bass.BaseExample;

public class SneedBidExample extends BaseExample {

	protected String orderByClause;
	protected boolean distinct;
	protected List<Criteria> oredCriteria;

	public SneedBidExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sme_sneed_bid
	 * 
	 * @mbggenerated Sun Apr 17 11:46:32 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sme_sneed_bid
	 * 
	 * @mbggenerated Sun Apr 17 11:46:32 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sme_sneed_bid
	 * 
	 * @mbggenerated Sun Apr 17 11:46:32 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sme_sneed_bid
	 * 
	 * @mbggenerated Sun Apr 17 11:46:32 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sme_sneed_bid
	 * 
	 * @mbggenerated Sun Apr 17 11:46:32 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sme_sneed_bid
	 * 
	 * @mbggenerated Sun Apr 17 11:46:32 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sme_sneed_bid
	 * 
	 * @mbggenerated Sun Apr 17 11:46:32 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sme_sneed_bid
	 * 
	 * @mbggenerated Sun Apr 17 11:46:32 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table sme_sneed_bid
	 * 
	 * @mbggenerated Sun Apr 17 11:46:32 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andSvgidIsNull() {
			addCriterion("svgid is null");
			return (Criteria) this;
		}

		public Criteria andSvgidIsNotNull() {
			addCriterion("svgid is not null");
			return (Criteria) this;
		}

		public Criteria andSvgidEqualTo(Long value) {
			addCriterion("svgid =", value, "svgid");
			return (Criteria) this;
		}

		public Criteria andSvgidNotEqualTo(Long value) {
			addCriterion("svgid <>", value, "svgid");
			return (Criteria) this;
		}

		public Criteria andSvgidGreaterThan(Long value) {
			addCriterion("svgid >", value, "svgid");
			return (Criteria) this;
		}

		public Criteria andSvgidGreaterThanOrEqualTo(Long value) {
			addCriterion("svgid >=", value, "svgid");
			return (Criteria) this;
		}

		public Criteria andSvgidLessThan(Long value) {
			addCriterion("svgid <", value, "svgid");
			return (Criteria) this;
		}

		public Criteria andSvgidLessThanOrEqualTo(Long value) {
			addCriterion("svgid <=", value, "svgid");
			return (Criteria) this;
		}

		public Criteria andSvgidIn(List<Long> values) {
			addCriterion("svgid in", values, "svgid");
			return (Criteria) this;
		}

		public Criteria andSvgidNotIn(List<Long> values) {
			addCriterion("svgid not in", values, "svgid");
			return (Criteria) this;
		}

		public Criteria andSvgidBetween(Long value1, Long value2) {
			addCriterion("svgid between", value1, value2, "svgid");
			return (Criteria) this;
		}

		public Criteria andSvgidNotBetween(Long value1, Long value2) {
			addCriterion("svgid not between", value1, value2, "svgid");
			return (Criteria) this;
		}

		public Criteria andLinktelIsNull() {
			addCriterion("linktel is null");
			return (Criteria) this;
		}

		public Criteria andLinktelIsNotNull() {
			addCriterion("linktel is not null");
			return (Criteria) this;
		}

		public Criteria andLinktelEqualTo(String value) {
			addCriterion("linktel =", value, "linktel");
			return (Criteria) this;
		}

		public Criteria andLinktelNotEqualTo(String value) {
			addCriterion("linktel <>", value, "linktel");
			return (Criteria) this;
		}

		public Criteria andLinktelGreaterThan(String value) {
			addCriterion("linktel >", value, "linktel");
			return (Criteria) this;
		}

		public Criteria andLinktelGreaterThanOrEqualTo(String value) {
			addCriterion("linktel >=", value, "linktel");
			return (Criteria) this;
		}

		public Criteria andLinktelLessThan(String value) {
			addCriterion("linktel <", value, "linktel");
			return (Criteria) this;
		}

		public Criteria andLinktelLessThanOrEqualTo(String value) {
			addCriterion("linktel <=", value, "linktel");
			return (Criteria) this;
		}

		public Criteria andLinktelLike(String value) {
			addCriterion("linktel like", value, "linktel");
			return (Criteria) this;
		}

		public Criteria andLinktelNotLike(String value) {
			addCriterion("linktel not like", value, "linktel");
			return (Criteria) this;
		}

		public Criteria andLinktelIn(List<String> values) {
			addCriterion("linktel in", values, "linktel");
			return (Criteria) this;
		}

		public Criteria andLinktelNotIn(List<String> values) {
			addCriterion("linktel not in", values, "linktel");
			return (Criteria) this;
		}

		public Criteria andLinktelBetween(String value1, String value2) {
			addCriterion("linktel between", value1, value2, "linktel");
			return (Criteria) this;
		}

		public Criteria andLinktelNotBetween(String value1, String value2) {
			addCriterion("linktel not between", value1, value2, "linktel");
			return (Criteria) this;
		}

		public Criteria andLinkerIsNull() {
			addCriterion("linker is null");
			return (Criteria) this;
		}

		public Criteria andLinkerIsNotNull() {
			addCriterion("linker is not null");
			return (Criteria) this;
		}

		public Criteria andLinkerEqualTo(String value) {
			addCriterion("linker =", value, "linker");
			return (Criteria) this;
		}

		public Criteria andLinkerNotEqualTo(String value) {
			addCriterion("linker <>", value, "linker");
			return (Criteria) this;
		}

		public Criteria andLinkerGreaterThan(String value) {
			addCriterion("linker >", value, "linker");
			return (Criteria) this;
		}

		public Criteria andLinkerGreaterThanOrEqualTo(String value) {
			addCriterion("linker >=", value, "linker");
			return (Criteria) this;
		}

		public Criteria andLinkerLessThan(String value) {
			addCriterion("linker <", value, "linker");
			return (Criteria) this;
		}

		public Criteria andLinkerLessThanOrEqualTo(String value) {
			addCriterion("linker <=", value, "linker");
			return (Criteria) this;
		}

		public Criteria andLinkerLike(String value) {
			addCriterion("linker like", value, "linker");
			return (Criteria) this;
		}

		public Criteria andLinkerNotLike(String value) {
			addCriterion("linker not like", value, "linker");
			return (Criteria) this;
		}

		public Criteria andLinkerIn(List<String> values) {
			addCriterion("linker in", values, "linker");
			return (Criteria) this;
		}

		public Criteria andLinkerNotIn(List<String> values) {
			addCriterion("linker not in", values, "linker");
			return (Criteria) this;
		}

		public Criteria andLinkerBetween(String value1, String value2) {
			addCriterion("linker between", value1, value2, "linker");
			return (Criteria) this;
		}

		public Criteria andLinkerNotBetween(String value1, String value2) {
			addCriterion("linker not between", value1, value2, "linker");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andEvalnumIsNull() {
			addCriterion("evalnum is null");
			return (Criteria) this;
		}

		public Criteria andEvalnumIsNotNull() {
			addCriterion("evalnum is not null");
			return (Criteria) this;
		}

		public Criteria andEvalnumEqualTo(Integer value) {
			addCriterion("evalnum =", value, "evalnum");
			return (Criteria) this;
		}

		public Criteria andEvalnumNotEqualTo(Integer value) {
			addCriterion("evalnum <>", value, "evalnum");
			return (Criteria) this;
		}

		public Criteria andEvalnumGreaterThan(Integer value) {
			addCriterion("evalnum >", value, "evalnum");
			return (Criteria) this;
		}

		public Criteria andEvalnumGreaterThanOrEqualTo(Integer value) {
			addCriterion("evalnum >=", value, "evalnum");
			return (Criteria) this;
		}

		public Criteria andEvalnumLessThan(Integer value) {
			addCriterion("evalnum <", value, "evalnum");
			return (Criteria) this;
		}

		public Criteria andEvalnumLessThanOrEqualTo(Integer value) {
			addCriterion("evalnum <=", value, "evalnum");
			return (Criteria) this;
		}

		public Criteria andEvalnumIn(List<Integer> values) {
			addCriterion("evalnum in", values, "evalnum");
			return (Criteria) this;
		}

		public Criteria andEvalnumNotIn(List<Integer> values) {
			addCriterion("evalnum not in", values, "evalnum");
			return (Criteria) this;
		}

		public Criteria andEvalnumBetween(Integer value1, Integer value2) {
			addCriterion("evalnum between", value1, value2, "evalnum");
			return (Criteria) this;
		}

		public Criteria andEvalnumNotBetween(Integer value1, Integer value2) {
			addCriterion("evalnum not between", value1, value2, "evalnum");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNull() {
			addCriterion("addtime is null");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNotNull() {
			addCriterion("addtime is not null");
			return (Criteria) this;
		}

		public Criteria andAddtimeEqualTo(Date value) {
			addCriterion("addtime =", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotEqualTo(Date value) {
			addCriterion("addtime <>", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThan(Date value) {
			addCriterion("addtime >", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("addtime >=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThan(Date value) {
			addCriterion("addtime <", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThanOrEqualTo(Date value) {
			addCriterion("addtime <=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeIn(List<Date> values) {
			addCriterion("addtime in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotIn(List<Date> values) {
			addCriterion("addtime not in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeBetween(Date value1, Date value2) {
			addCriterion("addtime between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotBetween(Date value1, Date value2) {
			addCriterion("addtime not between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andLasttimeIsNull() {
			addCriterion("lasttime is null");
			return (Criteria) this;
		}

		public Criteria andLasttimeIsNotNull() {
			addCriterion("lasttime is not null");
			return (Criteria) this;
		}

		public Criteria andLasttimeEqualTo(Date value) {
			addCriterion("lasttime =", value, "lasttime");
			return (Criteria) this;
		}

		public Criteria andLasttimeNotEqualTo(Date value) {
			addCriterion("lasttime <>", value, "lasttime");
			return (Criteria) this;
		}

		public Criteria andLasttimeGreaterThan(Date value) {
			addCriterion("lasttime >", value, "lasttime");
			return (Criteria) this;
		}

		public Criteria andLasttimeGreaterThanOrEqualTo(Date value) {
			addCriterion("lasttime >=", value, "lasttime");
			return (Criteria) this;
		}

		public Criteria andLasttimeLessThan(Date value) {
			addCriterion("lasttime <", value, "lasttime");
			return (Criteria) this;
		}

		public Criteria andLasttimeLessThanOrEqualTo(Date value) {
			addCriterion("lasttime <=", value, "lasttime");
			return (Criteria) this;
		}

		public Criteria andLasttimeIn(List<Date> values) {
			addCriterion("lasttime in", values, "lasttime");
			return (Criteria) this;
		}

		public Criteria andLasttimeNotIn(List<Date> values) {
			addCriterion("lasttime not in", values, "lasttime");
			return (Criteria) this;
		}

		public Criteria andLasttimeBetween(Date value1, Date value2) {
			addCriterion("lasttime between", value1, value2, "lasttime");
			return (Criteria) this;
		}

		public Criteria andLasttimeNotBetween(Date value1, Date value2) {
			addCriterion("lasttime not between", value1, value2, "lasttime");
			return (Criteria) this;
		}

		public Criteria andIstonedIsNull() {
			addCriterion("istoned is null");
			return (Criteria) this;
		}

		public Criteria andIstonedIsNotNull() {
			addCriterion("istoned is not null");
			return (Criteria) this;
		}

		public Criteria andIstonedEqualTo(String value) {
			addCriterion("istoned =", value, "istoned");
			return (Criteria) this;
		}

		public Criteria andIstonedNotEqualTo(String value) {
			addCriterion("istoned <>", value, "istoned");
			return (Criteria) this;
		}

		public Criteria andIstonedGreaterThan(String value) {
			addCriterion("istoned >", value, "istoned");
			return (Criteria) this;
		}

		public Criteria andIstonedGreaterThanOrEqualTo(String value) {
			addCriterion("istoned >=", value, "istoned");
			return (Criteria) this;
		}

		public Criteria andIstonedLessThan(String value) {
			addCriterion("istoned <", value, "istoned");
			return (Criteria) this;
		}

		public Criteria andIstonedLessThanOrEqualTo(String value) {
			addCriterion("istoned <=", value, "istoned");
			return (Criteria) this;
		}

		public Criteria andIstonedLike(String value) {
			addCriterion("istoned like", value, "istoned");
			return (Criteria) this;
		}

		public Criteria andIstonedNotLike(String value) {
			addCriterion("istoned not like", value, "istoned");
			return (Criteria) this;
		}

		public Criteria andIstonedIn(List<String> values) {
			addCriterion("istoned in", values, "istoned");
			return (Criteria) this;
		}

		public Criteria andIstonedNotIn(List<String> values) {
			addCriterion("istoned not in", values, "istoned");
			return (Criteria) this;
		}

		public Criteria andIstonedBetween(String value1, String value2) {
			addCriterion("istoned between", value1, value2, "istoned");
			return (Criteria) this;
		}

		public Criteria andIstonedNotBetween(String value1, String value2) {
			addCriterion("istoned not between", value1, value2, "istoned");
			return (Criteria) this;
		}

		public Criteria andSneedidIsNull() {
			addCriterion("sneedid is null");
			return (Criteria) this;
		}

		public Criteria andSneedidIsNotNull() {
			addCriterion("sneedid is not null");
			return (Criteria) this;
		}

		public Criteria andSneedidEqualTo(Long value) {
			addCriterion("sneedid =", value, "sneedid");
			return (Criteria) this;
		}

		public Criteria andSneedidNotEqualTo(Long value) {
			addCriterion("sneedid <>", value, "sneedid");
			return (Criteria) this;
		}

		public Criteria andSneedidGreaterThan(Long value) {
			addCriterion("sneedid >", value, "sneedid");
			return (Criteria) this;
		}

		public Criteria andSneedidGreaterThanOrEqualTo(Long value) {
			addCriterion("sneedid >=", value, "sneedid");
			return (Criteria) this;
		}

		public Criteria andSneedidLessThan(Long value) {
			addCriterion("sneedid <", value, "sneedid");
			return (Criteria) this;
		}

		public Criteria andSneedidLessThanOrEqualTo(Long value) {
			addCriterion("sneedid <=", value, "sneedid");
			return (Criteria) this;
		}

		public Criteria andSneedidIn(List<Long> values) {
			addCriterion("sneedid in", values, "sneedid");
			return (Criteria) this;
		}

		public Criteria andSneedidNotIn(List<Long> values) {
			addCriterion("sneedid not in", values, "sneedid");
			return (Criteria) this;
		}

		public Criteria andSneedidBetween(Long value1, Long value2) {
			addCriterion("sneedid between", value1, value2, "sneedid");
			return (Criteria) this;
		}

		public Criteria andSneedidNotBetween(Long value1, Long value2) {
			addCriterion("sneedid not between", value1, value2, "sneedid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table sme_sneed_bid
	 * 
	 * @mbggenerated do_not_delete_during_merge Sun Apr 17 11:46:32 CST 2016
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table sme_sneed_bid
	 * 
	 * @mbggenerated Sun Apr 17 11:46:32 CST 2016
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}