package com.gsccs.sme.plat.svg.model;

import java.util.ArrayList;
import java.util.List;

import com.gsccs.sme.plat.bass.BaseExample;

public class SvorgTExample extends BaseExample{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sme_svorg
     *
     * @mbggenerated Thu Mar 17 11:21:56 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sme_svorg
     *
     * @mbggenerated Thu Mar 17 11:21:56 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sme_svorg
     *
     * @mbggenerated Thu Mar 17 11:21:56 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_svorg
     *
     * @mbggenerated Thu Mar 17 11:21:56 CST 2016
     */
    public SvorgTExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_svorg
     *
     * @mbggenerated Thu Mar 17 11:21:56 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_svorg
     *
     * @mbggenerated Thu Mar 17 11:21:56 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_svorg
     *
     * @mbggenerated Thu Mar 17 11:21:56 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_svorg
     *
     * @mbggenerated Thu Mar 17 11:21:56 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_svorg
     *
     * @mbggenerated Thu Mar 17 11:21:56 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_svorg
     *
     * @mbggenerated Thu Mar 17 11:21:56 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_svorg
     *
     * @mbggenerated Thu Mar 17 11:21:56 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_svorg
     *
     * @mbggenerated Thu Mar 17 11:21:56 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_svorg
     *
     * @mbggenerated Thu Mar 17 11:21:56 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_svorg
     *
     * @mbggenerated Thu Mar 17 11:21:56 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sme_svorg
     *
     * @mbggenerated Thu Mar 17 11:21:56 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        
        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andDomainIsNull() {
            addCriterion("domain is null");
            return (Criteria) this;
        }

        public Criteria andDomainIsNotNull() {
            addCriterion("domain is not null");
            return (Criteria) this;
        }

        public Criteria andDomainEqualTo(String value) {
            addCriterion("domain =", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotEqualTo(String value) {
            addCriterion("domain <>", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainGreaterThan(String value) {
            addCriterion("domain >", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainGreaterThanOrEqualTo(String value) {
            addCriterion("domain >=", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLessThan(String value) {
            addCriterion("domain <", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLessThanOrEqualTo(String value) {
            addCriterion("domain <=", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLike(String value) {
            addCriterion("domain like", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotLike(String value) {
            addCriterion("domain not like", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainIn(List<String> values) {
            addCriterion("domain in", values, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotIn(List<String> values) {
            addCriterion("domain not in", values, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainBetween(String value1, String value2) {
            addCriterion("domain between", value1, value2, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotBetween(String value1, String value2) {
            addCriterion("domain not between", value1, value2, "domain");
            return (Criteria) this;
        }

        public Criteria andNatureIsNull() {
            addCriterion("nature is null");
            return (Criteria) this;
        }

        public Criteria andNatureIsNotNull() {
            addCriterion("nature is not null");
            return (Criteria) this;
        }

        public Criteria andNatureEqualTo(String value) {
            addCriterion("nature =", value, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureNotEqualTo(String value) {
            addCriterion("nature <>", value, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureLike(String value) {
            addCriterion("nature like", value, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureNotLike(String value) {
            addCriterion("nature not like", value, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureIn(List<String> values) {
            addCriterion("nature in", values, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureNotIn(List<String> values) {
            addCriterion("nature not in", values, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureBetween(String value1, String value2) {
            addCriterion("nature between", value1, value2, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureNotBetween(String value1, String value2) {
            addCriterion("nature not between", value1, value2, "nature");
            return (Criteria) this;
        }

        public Criteria andLegalerIsNull() {
            addCriterion("legaler is null");
            return (Criteria) this;
        }

        public Criteria andLegalerIsNotNull() {
            addCriterion("legaler is not null");
            return (Criteria) this;
        }

        public Criteria andLegalerEqualTo(String value) {
            addCriterion("legaler =", value, "legaler");
            return (Criteria) this;
        }

        public Criteria andLegalerNotEqualTo(String value) {
            addCriterion("legaler <>", value, "legaler");
            return (Criteria) this;
        }

        public Criteria andLegalerGreaterThan(String value) {
            addCriterion("legaler >", value, "legaler");
            return (Criteria) this;
        }

        public Criteria andLegalerGreaterThanOrEqualTo(String value) {
            addCriterion("legaler >=", value, "legaler");
            return (Criteria) this;
        }

        public Criteria andLegalerLessThan(String value) {
            addCriterion("legaler <", value, "legaler");
            return (Criteria) this;
        }

        public Criteria andLegalerLessThanOrEqualTo(String value) {
            addCriterion("legaler <=", value, "legaler");
            return (Criteria) this;
        }

        public Criteria andLegalerLike(String value) {
            addCriterion("legaler like", value, "legaler");
            return (Criteria) this;
        }

        public Criteria andLegalerNotLike(String value) {
            addCriterion("legaler not like", value, "legaler");
            return (Criteria) this;
        }

        public Criteria andLegalerIn(List<String> values) {
            addCriterion("legaler in", values, "legaler");
            return (Criteria) this;
        }

        public Criteria andLegalerNotIn(List<String> values) {
            addCriterion("legaler not in", values, "legaler");
            return (Criteria) this;
        }

        public Criteria andLegalerBetween(String value1, String value2) {
            addCriterion("legaler between", value1, value2, "legaler");
            return (Criteria) this;
        }

        public Criteria andLegalerNotBetween(String value1, String value2) {
            addCriterion("legaler not between", value1, value2, "legaler");
            return (Criteria) this;
        }

        public Criteria andLinkerIsNull() {
            addCriterion("linker is null");
            return (Criteria) this;
        }

        public Criteria andLinkerIsNotNull() {
            addCriterion("linker is not null");
            return (Criteria) this;
        }

        public Criteria andLinkerEqualTo(String value) {
            addCriterion("linker =", value, "linker");
            return (Criteria) this;
        }

        public Criteria andLinkerNotEqualTo(String value) {
            addCriterion("linker <>", value, "linker");
            return (Criteria) this;
        }

        public Criteria andLinkerLike(String value) {
            addCriterion("linker like", value, "linker");
            return (Criteria) this;
        }

        public Criteria andLinkerNotLike(String value) {
            addCriterion("linker not like", value, "linker");
            return (Criteria) this;
        }

        public Criteria andLinkerIn(List<String> values) {
            addCriterion("linker in", values, "linker");
            return (Criteria) this;
        }

        public Criteria andLinkerNotIn(List<String> values) {
            addCriterion("linker not in", values, "linker");
            return (Criteria) this;
        }

        public Criteria andLinkerBetween(String value1, String value2) {
            addCriterion("linker between", value1, value2, "linker");
            return (Criteria) this;
        }

        public Criteria andLinkerNotBetween(String value1, String value2) {
            addCriterion("linker not between", value1, value2, "linker");
            return (Criteria) this;
        }

        public Criteria andLinktelIsNull() {
            addCriterion("linktel is null");
            return (Criteria) this;
        }

        public Criteria andLinktelIsNotNull() {
            addCriterion("linktel is not null");
            return (Criteria) this;
        }

        public Criteria andLinktelEqualTo(String value) {
            addCriterion("linktel =", value, "linktel");
            return (Criteria) this;
        }

        public Criteria andLinktelNotEqualTo(String value) {
            addCriterion("linktel <>", value, "linktel");
            return (Criteria) this;
        }

        

        public Criteria andLinktelLike(String value) {
            addCriterion("linktel like", value, "linktel");
            return (Criteria) this;
        }

        public Criteria andLinktelNotLike(String value) {
            addCriterion("linktel not like", value, "linktel");
            return (Criteria) this;
        }

        public Criteria andLinktelIn(List<String> values) {
            addCriterion("linktel in", values, "linktel");
            return (Criteria) this;
        }

        public Criteria andLinktelNotIn(List<String> values) {
            addCriterion("linktel not in", values, "linktel");
            return (Criteria) this;
        }

        public Criteria andLinktelBetween(String value1, String value2) {
            addCriterion("linktel between", value1, value2, "linktel");
            return (Criteria) this;
        }

        public Criteria andLinktelNotBetween(String value1, String value2) {
            addCriterion("linktel not between", value1, value2, "linktel");
            return (Criteria) this;
        }

        public Criteria andSremarkIsNull() {
            addCriterion("sremark is null");
            return (Criteria) this;
        }

        public Criteria andSremarkIsNotNull() {
            addCriterion("sremark is not null");
            return (Criteria) this;
        }

        public Criteria andSremarkEqualTo(String value) {
            addCriterion("sremark =", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkNotEqualTo(String value) {
            addCriterion("sremark <>", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkLike(String value) {
            addCriterion("sremark like", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkNotLike(String value) {
            addCriterion("sremark not like", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkIn(List<String> values) {
            addCriterion("sremark in", values, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkNotIn(List<String> values) {
            addCriterion("sremark not in", values, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkBetween(String value1, String value2) {
            addCriterion("sremark between", value1, value2, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkNotBetween(String value1, String value2) {
            addCriterion("sremark not between", value1, value2, "sremark");
            return (Criteria) this;
        }

        public Criteria andScodeIsNull() {
            addCriterion("scode is null");
            return (Criteria) this;
        }

        public Criteria andScodeIsNotNull() {
            addCriterion("scode is not null");
            return (Criteria) this;
        }

        public Criteria andScodeEqualTo(String value) {
            addCriterion("scode =", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeNotEqualTo(String value) {
            addCriterion("scode <>", value, "scode");
            return (Criteria) this;
        }

        

        public Criteria andScodeLike(String value) {
            addCriterion("scode like", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeNotLike(String value) {
            addCriterion("scode not like", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeIn(List<String> values) {
            addCriterion("scode in", values, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeNotIn(List<String> values) {
            addCriterion("scode not in", values, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeBetween(String value1, String value2) {
            addCriterion("scode between", value1, value2, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeNotBetween(String value1, String value2) {
            addCriterion("scode not between", value1, value2, "scode");
            return (Criteria) this;
        }

        public Criteria andSsubcodeIsNull() {
            addCriterion("subscode is null");
            return (Criteria) this;
        }

        public Criteria andSsubcodeIsNotNull() {
            addCriterion("subscode is not null");
            return (Criteria) this;
        }

        public Criteria andSubscodeEqualTo(String value) {
            addCriterion("subscode =", value, "subscode");
            return (Criteria) this;
        }

        public Criteria andSubscodeNotEqualTo(String value) {
            addCriterion("subscode <>", value, "subscode");
            return (Criteria) this;
        }

        

        public Criteria andSsubcodeLike(String value) {
            addCriterion("subscode like", value, "subscode");
            return (Criteria) this;
        }

        public Criteria andSsubcodeNotLike(String value) {
            addCriterion("subscode not like", value, "subscode");
            return (Criteria) this;
        }

        public Criteria andSsubcodeIn(List<String> values) {
            addCriterion("subscode in", values, "subscode");
            return (Criteria) this;
        }

        public Criteria andSsubcodeNotIn(List<String> values) {
            addCriterion("subscode not in", values, "subscode");
            return (Criteria) this;
        }


        public Criteria andOrgcodeIsNull() {
            addCriterion("orgcode is null");
            return (Criteria) this;
        }

        public Criteria andOrgcodeIsNotNull() {
            addCriterion("orgcode is not null");
            return (Criteria) this;
        }

        public Criteria andOrgcodeEqualTo(String value) {
            addCriterion("orgcode =", value, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeNotEqualTo(String value) {
            addCriterion("orgcode <>", value, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeGreaterThan(String value) {
            addCriterion("orgcode >", value, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeGreaterThanOrEqualTo(String value) {
            addCriterion("orgcode >=", value, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeLessThan(String value) {
            addCriterion("orgcode <", value, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeLessThanOrEqualTo(String value) {
            addCriterion("orgcode <=", value, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeLike(String value) {
            addCriterion("orgcode like", value, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeNotLike(String value) {
            addCriterion("orgcode not like", value, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeIn(List<String> values) {
            addCriterion("orgcode in", values, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeNotIn(List<String> values) {
            addCriterion("orgcode not in", values, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeBetween(String value1, String value2) {
            addCriterion("orgcode between", value1, value2, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeNotBetween(String value1, String value2) {
            addCriterion("orgcode not between", value1, value2, "orgcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeIsNull() {
            addCriterion("regcode is null");
            return (Criteria) this;
        }

        public Criteria andRegcodeIsNotNull() {
            addCriterion("regcode is not null");
            return (Criteria) this;
        }

        public Criteria andRegcodeEqualTo(String value) {
            addCriterion("regcode =", value, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeNotEqualTo(String value) {
            addCriterion("regcode <>", value, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeGreaterThan(String value) {
            addCriterion("regcode >", value, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeGreaterThanOrEqualTo(String value) {
            addCriterion("regcode >=", value, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeLessThan(String value) {
            addCriterion("regcode <", value, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeLessThanOrEqualTo(String value) {
            addCriterion("regcode <=", value, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeLike(String value) {
            addCriterion("regcode like", value, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeNotLike(String value) {
            addCriterion("regcode not like", value, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeIn(List<String> values) {
            addCriterion("regcode in", values, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeNotIn(List<String> values) {
            addCriterion("regcode not in", values, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeBetween(String value1, String value2) {
            addCriterion("regcode between", value1, value2, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeNotBetween(String value1, String value2) {
            addCriterion("regcode not between", value1, value2, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegtypeIsNull() {
            addCriterion("regtype is null");
            return (Criteria) this;
        }

        public Criteria andRegtypeIsNotNull() {
            addCriterion("regtype is not null");
            return (Criteria) this;
        }

        public Criteria andRegtypeEqualTo(String value) {
            addCriterion("regtype =", value, "regtype");
            return (Criteria) this;
        }

        public Criteria andRegtypeNotEqualTo(String value) {
            addCriterion("regtype <>", value, "regtype");
            return (Criteria) this;
        }

        public Criteria andRegtypeGreaterThan(String value) {
            addCriterion("regtype >", value, "regtype");
            return (Criteria) this;
        }

        public Criteria andRegtypeGreaterThanOrEqualTo(String value) {
            addCriterion("regtype >=", value, "regtype");
            return (Criteria) this;
        }

        public Criteria andRegtypeLessThan(String value) {
            addCriterion("regtype <", value, "regtype");
            return (Criteria) this;
        }

        public Criteria andRegtypeLessThanOrEqualTo(String value) {
            addCriterion("regtype <=", value, "regtype");
            return (Criteria) this;
        }

        public Criteria andRegtypeLike(String value) {
            addCriterion("regtype like", value, "regtype");
            return (Criteria) this;
        }

        public Criteria andRegtypeNotLike(String value) {
            addCriterion("regtype not like", value, "regtype");
            return (Criteria) this;
        }

        public Criteria andRegtypeIn(List<String> values) {
            addCriterion("regtype in", values, "regtype");
            return (Criteria) this;
        }

        public Criteria andRegtypeNotIn(List<String> values) {
            addCriterion("regtype not in", values, "regtype");
            return (Criteria) this;
        }

        public Criteria andRegtypeBetween(String value1, String value2) {
            addCriterion("regtype between", value1, value2, "regtype");
            return (Criteria) this;
        }

        public Criteria andRegtypeNotBetween(String value1, String value2) {
            addCriterion("regtype not between", value1, value2, "regtype");
            return (Criteria) this;
        }

        public Criteria andHycodeIsNull() {
            addCriterion("hycode is null");
            return (Criteria) this;
        }

        public Criteria andHycodeIsNotNull() {
            addCriterion("hycode is not null");
            return (Criteria) this;
        }

        public Criteria andHycodeEqualTo(String value) {
            addCriterion("hycode =", value, "hycode");
            return (Criteria) this;
        }

        public Criteria andHycodeNotEqualTo(String value) {
            addCriterion("hycode <>", value, "hycode");
            return (Criteria) this;
        }

        public Criteria andHycodeIn(List<String> values) {
            addCriterion("hycode in", values, "hycode");
            return (Criteria) this;
        }

        public Criteria andHycodeNotIn(List<String> values) {
            addCriterion("hycode not in", values, "hycode");
            return (Criteria) this;
        }

        public Criteria andHycodeBetween(String value1, String value2) {
            addCriterion("hycode between", value1, value2, "hycode");
            return (Criteria) this;
        }

        public Criteria andHycodeNotBetween(String value1, String value2) {
            addCriterion("hycode not between", value1, value2, "hycode");
            return (Criteria) this;
        }

        public Criteria andStakeIsNull() {
            addCriterion("stake is null");
            return (Criteria) this;
        }

        public Criteria andStakeIsNotNull() {
            addCriterion("stake is not null");
            return (Criteria) this;
        }

        public Criteria andStakeEqualTo(String value) {
            addCriterion("stake =", value, "stake");
            return (Criteria) this;
        }

        public Criteria andStakeNotEqualTo(String value) {
            addCriterion("stake <>", value, "stake");
            return (Criteria) this;
        }

        public Criteria andStakeGreaterThan(String value) {
            addCriterion("stake >", value, "stake");
            return (Criteria) this;
        }

        public Criteria andStakeGreaterThanOrEqualTo(String value) {
            addCriterion("stake >=", value, "stake");
            return (Criteria) this;
        }

        public Criteria andStakeLessThan(String value) {
            addCriterion("stake <", value, "stake");
            return (Criteria) this;
        }

        public Criteria andStakeLessThanOrEqualTo(String value) {
            addCriterion("stake <=", value, "stake");
            return (Criteria) this;
        }

        public Criteria andStakeLike(String value) {
            addCriterion("stake like", value, "stake");
            return (Criteria) this;
        }

        public Criteria andStakeNotLike(String value) {
            addCriterion("stake not like", value, "stake");
            return (Criteria) this;
        }

        public Criteria andStakeIn(List<String> values) {
            addCriterion("stake in", values, "stake");
            return (Criteria) this;
        }

        public Criteria andStakeNotIn(List<String> values) {
            addCriterion("stake not in", values, "stake");
            return (Criteria) this;
        }

        public Criteria andStakeBetween(String value1, String value2) {
            addCriterion("stake between", value1, value2, "stake");
            return (Criteria) this;
        }

        public Criteria andStakeNotBetween(String value1, String value2) {
            addCriterion("stake not between", value1, value2, "stake");
            return (Criteria) this;
        }

        public Criteria andRegassetIsNull() {
            addCriterion("regasset is null");
            return (Criteria) this;
        }

        public Criteria andRegassetIsNotNull() {
            addCriterion("regasset is not null");
            return (Criteria) this;
        }

        public Criteria andRegassetEqualTo(Float value) {
            addCriterion("regasset =", value, "regasset");
            return (Criteria) this;
        }

        public Criteria andRegassetNotEqualTo(Float value) {
            addCriterion("regasset <>", value, "regasset");
            return (Criteria) this;
        }

        public Criteria andRegassetGreaterThan(Float value) {
            addCriterion("regasset >", value, "regasset");
            return (Criteria) this;
        }

        public Criteria andRegassetGreaterThanOrEqualTo(Float value) {
            addCriterion("regasset >=", value, "regasset");
            return (Criteria) this;
        }

        public Criteria andRegassetLessThan(Float value) {
            addCriterion("regasset <", value, "regasset");
            return (Criteria) this;
        }

        public Criteria andRegassetLessThanOrEqualTo(Float value) {
            addCriterion("regasset <=", value, "regasset");
            return (Criteria) this;
        }

        public Criteria andRegassetIn(List<Float> values) {
            addCriterion("regasset in", values, "regasset");
            return (Criteria) this;
        }

        public Criteria andRegassetNotIn(List<Float> values) {
            addCriterion("regasset not in", values, "regasset");
            return (Criteria) this;
        }

        public Criteria andRegassetBetween(Float value1, Float value2) {
            addCriterion("regasset between", value1, value2, "regasset");
            return (Criteria) this;
        }

        public Criteria andRegassetNotBetween(Float value1, Float value2) {
            addCriterion("regasset not between", value1, value2, "regasset");
            return (Criteria) this;
        }

        public Criteria andPcodeIsNull() {
            addCriterion("pcode is null");
            return (Criteria) this;
        }

        public Criteria andPcodeIsNotNull() {
            addCriterion("pcode is not null");
            return (Criteria) this;
        }

        public Criteria andPcodeEqualTo(String value) {
            addCriterion("pcode =", value, "pcode");
            return (Criteria) this;
        }

        public Criteria andPcodeNotEqualTo(String value) {
            addCriterion("pcode <>", value, "pcode");
            return (Criteria) this;
        }

        public Criteria andPcodeGreaterThan(String value) {
            addCriterion("pcode >", value, "pcode");
            return (Criteria) this;
        }

        public Criteria andPcodeGreaterThanOrEqualTo(String value) {
            addCriterion("pcode >=", value, "pcode");
            return (Criteria) this;
        }

        public Criteria andPcodeLessThan(String value) {
            addCriterion("pcode <", value, "pcode");
            return (Criteria) this;
        }

        public Criteria andPcodeLessThanOrEqualTo(String value) {
            addCriterion("pcode <=", value, "pcode");
            return (Criteria) this;
        }

        public Criteria andPcodeLike(String value) {
            addCriterion("pcode like", value, "pcode");
            return (Criteria) this;
        }

        public Criteria andPcodeNotLike(String value) {
            addCriterion("pcode not like", value, "pcode");
            return (Criteria) this;
        }

        public Criteria andPcodeIn(List<String> values) {
            addCriterion("pcode in", values, "pcode");
            return (Criteria) this;
        }

        public Criteria andPcodeNotIn(List<String> values) {
            addCriterion("pcode not in", values, "pcode");
            return (Criteria) this;
        }

        public Criteria andPcodeBetween(String value1, String value2) {
            addCriterion("pcode between", value1, value2, "pcode");
            return (Criteria) this;
        }

        public Criteria andPcodeNotBetween(String value1, String value2) {
            addCriterion("pcode not between", value1, value2, "pcode");
            return (Criteria) this;
        }

        public Criteria andCcodeIsNull() {
            addCriterion("ccode is null");
            return (Criteria) this;
        }

        public Criteria andCcodeIsNotNull() {
            addCriterion("ccode is not null");
            return (Criteria) this;
        }

        public Criteria andCcodeEqualTo(String value) {
            addCriterion("ccode =", value, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeNotEqualTo(String value) {
            addCriterion("ccode <>", value, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeGreaterThan(String value) {
            addCriterion("ccode >", value, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeGreaterThanOrEqualTo(String value) {
            addCriterion("ccode >=", value, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeLessThan(String value) {
            addCriterion("ccode <", value, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeLessThanOrEqualTo(String value) {
            addCriterion("ccode <=", value, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeLike(String value) {
            addCriterion("ccode like", value, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeNotLike(String value) {
            addCriterion("ccode not like", value, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeIn(List<String> values) {
            addCriterion("ccode in", values, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeNotIn(List<String> values) {
            addCriterion("ccode not in", values, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeBetween(String value1, String value2) {
            addCriterion("ccode between", value1, value2, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeNotBetween(String value1, String value2) {
            addCriterion("ccode not between", value1, value2, "ccode");
            return (Criteria) this;
        }

        public Criteria andAcodeIsNull() {
            addCriterion("acode is null");
            return (Criteria) this;
        }

        public Criteria andAcodeIsNotNull() {
            addCriterion("acode is not null");
            return (Criteria) this;
        }

        public Criteria andAcodeEqualTo(String value) {
            addCriterion("acode =", value, "acode");
            return (Criteria) this;
        }
        
        public Criteria andSvgtypeEqualTo(String value) {
            addCriterion("svgtype =", value, "svgtype");
            return (Criteria) this;
        }

        
        public Criteria andAcodeIn(List<String> values) {
            addCriterion("acode in", values, "acode");
            return (Criteria) this;
        }

        public Criteria andAcodeNotIn(List<String> values) {
            addCriterion("acode not in", values, "acode");
            return (Criteria) this;
        }

        

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }


        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andProfqualifIsNull() {
            addCriterion("profqualif is null");
            return (Criteria) this;
        }

        public Criteria andProfqualifIsNotNull() {
            addCriterion("profqualif is not null");
            return (Criteria) this;
        }

        public Criteria andProfqualifEqualTo(String value) {
            addCriterion("profqualif =", value, "profqualif");
            return (Criteria) this;
        }

        public Criteria andProfqualifNotEqualTo(String value) {
            addCriterion("profqualif <>", value, "profqualif");
            return (Criteria) this;
        }

        public Criteria andProfqualifGreaterThan(String value) {
            addCriterion("profqualif >", value, "profqualif");
            return (Criteria) this;
        }

        public Criteria andProfqualifGreaterThanOrEqualTo(String value) {
            addCriterion("profqualif >=", value, "profqualif");
            return (Criteria) this;
        }

        public Criteria andProfqualifLessThan(String value) {
            addCriterion("profqualif <", value, "profqualif");
            return (Criteria) this;
        }

        public Criteria andProfqualifLessThanOrEqualTo(String value) {
            addCriterion("profqualif <=", value, "profqualif");
            return (Criteria) this;
        }

        public Criteria andProfqualifLike(String value) {
            addCriterion("profqualif like", value, "profqualif");
            return (Criteria) this;
        }

        public Criteria andProfqualifNotLike(String value) {
            addCriterion("profqualif not like", value, "profqualif");
            return (Criteria) this;
        }

        public Criteria andProfqualifIn(List<String> values) {
            addCriterion("profqualif in", values, "profqualif");
            return (Criteria) this;
        }

        public Criteria andProfqualifNotIn(List<String> values) {
            addCriterion("profqualif not in", values, "profqualif");
            return (Criteria) this;
        }

        public Criteria andProfqualifBetween(String value1, String value2) {
            addCriterion("profqualif between", value1, value2, "profqualif");
            return (Criteria) this;
        }

        public Criteria andProfqualifNotBetween(String value1, String value2) {
            addCriterion("profqualif not between", value1, value2, "profqualif");
            return (Criteria) this;
        }

        public Criteria andEqucondIsNull() {
            addCriterion("equcond is null");
            return (Criteria) this;
        }

        public Criteria andEqucondIsNotNull() {
            addCriterion("equcond is not null");
            return (Criteria) this;
        }

        public Criteria andEqucondEqualTo(String value) {
            addCriterion("equcond =", value, "equcond");
            return (Criteria) this;
        }

        public Criteria andEqucondNotEqualTo(String value) {
            addCriterion("equcond <>", value, "equcond");
            return (Criteria) this;
        }

        public Criteria andEqucondGreaterThan(String value) {
            addCriterion("equcond >", value, "equcond");
            return (Criteria) this;
        }

        public Criteria andEqucondGreaterThanOrEqualTo(String value) {
            addCriterion("equcond >=", value, "equcond");
            return (Criteria) this;
        }

        public Criteria andEqucondLessThan(String value) {
            addCriterion("equcond <", value, "equcond");
            return (Criteria) this;
        }

        public Criteria andEqucondLessThanOrEqualTo(String value) {
            addCriterion("equcond <=", value, "equcond");
            return (Criteria) this;
        }

        public Criteria andEqucondLike(String value) {
            addCriterion("equcond like", value, "equcond");
            return (Criteria) this;
        }

        public Criteria andEqucondNotLike(String value) {
            addCriterion("equcond not like", value, "equcond");
            return (Criteria) this;
        }

        public Criteria andEqucondIn(List<String> values) {
            addCriterion("equcond in", values, "equcond");
            return (Criteria) this;
        }

        public Criteria andEqucondNotIn(List<String> values) {
            addCriterion("equcond not in", values, "equcond");
            return (Criteria) this;
        }

        public Criteria andEqucondBetween(String value1, String value2) {
            addCriterion("equcond between", value1, value2, "equcond");
            return (Criteria) this;
        }

        public Criteria andEqucondNotBetween(String value1, String value2) {
            addCriterion("equcond not between", value1, value2, "equcond");
            return (Criteria) this;
        }

        public Criteria andPersonnelIsNull() {
            addCriterion("personnel is null");
            return (Criteria) this;
        }

        public Criteria andPersonnelIsNotNull() {
            addCriterion("personnel is not null");
            return (Criteria) this;
        }

        public Criteria andPersonnelEqualTo(String value) {
            addCriterion("personnel =", value, "personnel");
            return (Criteria) this;
        }

        public Criteria andPersonnelNotEqualTo(String value) {
            addCriterion("personnel <>", value, "personnel");
            return (Criteria) this;
        }

        public Criteria andPersonnelGreaterThan(String value) {
            addCriterion("personnel >", value, "personnel");
            return (Criteria) this;
        }

        public Criteria andPersonnelGreaterThanOrEqualTo(String value) {
            addCriterion("personnel >=", value, "personnel");
            return (Criteria) this;
        }

        public Criteria andPersonnelLessThan(String value) {
            addCriterion("personnel <", value, "personnel");
            return (Criteria) this;
        }

        public Criteria andPersonnelLessThanOrEqualTo(String value) {
            addCriterion("personnel <=", value, "personnel");
            return (Criteria) this;
        }

        public Criteria andPersonnelLike(String value) {
            addCriterion("personnel like", value, "personnel");
            return (Criteria) this;
        }

        public Criteria andPersonnelNotLike(String value) {
            addCriterion("personnel not like", value, "personnel");
            return (Criteria) this;
        }

        public Criteria andPersonnelIn(List<String> values) {
            addCriterion("personnel in", values, "personnel");
            return (Criteria) this;
        }

        public Criteria andPersonnelNotIn(List<String> values) {
            addCriterion("personnel not in", values, "personnel");
            return (Criteria) this;
        }

        public Criteria andPersonnelBetween(String value1, String value2) {
            addCriterion("personnel between", value1, value2, "personnel");
            return (Criteria) this;
        }

        public Criteria andPersonnelNotBetween(String value1, String value2) {
            addCriterion("personnel not between", value1, value2, "personnel");
            return (Criteria) this;
        }

        public Criteria andOrgcodeimgIsNull() {
            addCriterion("orgcodeimg is null");
            return (Criteria) this;
        }

        public Criteria andOrgcodeimgIsNotNull() {
            addCriterion("orgcodeimg is not null");
            return (Criteria) this;
        }

        public Criteria andOrgcodeimgEqualTo(String value) {
            addCriterion("orgcodeimg =", value, "orgcodeimg");
            return (Criteria) this;
        }

        public Criteria andOrgcodeimgNotEqualTo(String value) {
            addCriterion("orgcodeimg <>", value, "orgcodeimg");
            return (Criteria) this;
        }

        public Criteria andOrgcodeimgGreaterThan(String value) {
            addCriterion("orgcodeimg >", value, "orgcodeimg");
            return (Criteria) this;
        }

        public Criteria andOrgcodeimgGreaterThanOrEqualTo(String value) {
            addCriterion("orgcodeimg >=", value, "orgcodeimg");
            return (Criteria) this;
        }

        public Criteria andOrgcodeimgLessThan(String value) {
            addCriterion("orgcodeimg <", value, "orgcodeimg");
            return (Criteria) this;
        }

        public Criteria andOrgcodeimgLessThanOrEqualTo(String value) {
            addCriterion("orgcodeimg <=", value, "orgcodeimg");
            return (Criteria) this;
        }

        public Criteria andOrgcodeimgLike(String value) {
            addCriterion("orgcodeimg like", value, "orgcodeimg");
            return (Criteria) this;
        }

        public Criteria andOrgcodeimgNotLike(String value) {
            addCriterion("orgcodeimg not like", value, "orgcodeimg");
            return (Criteria) this;
        }

        public Criteria andOrgcodeimgIn(List<String> values) {
            addCriterion("orgcodeimg in", values, "orgcodeimg");
            return (Criteria) this;
        }

        public Criteria andOrgcodeimgNotIn(List<String> values) {
            addCriterion("orgcodeimg not in", values, "orgcodeimg");
            return (Criteria) this;
        }

        public Criteria andOrgcodeimgBetween(String value1, String value2) {
            addCriterion("orgcodeimg between", value1, value2, "orgcodeimg");
            return (Criteria) this;
        }

        public Criteria andOrgcodeimgNotBetween(String value1, String value2) {
            addCriterion("orgcodeimg not between", value1, value2, "orgcodeimg");
            return (Criteria) this;
        }

        public Criteria andRegcodeimgIsNull() {
            addCriterion("regcodeimg is null");
            return (Criteria) this;
        }

        public Criteria andRegcodeimgIsNotNull() {
            addCriterion("regcodeimg is not null");
            return (Criteria) this;
        }

        public Criteria andRegcodeimgEqualTo(String value) {
            addCriterion("regcodeimg =", value, "regcodeimg");
            return (Criteria) this;
        }

        public Criteria andRegcodeimgNotEqualTo(String value) {
            addCriterion("regcodeimg <>", value, "regcodeimg");
            return (Criteria) this;
        }

        public Criteria andRegcodeimgGreaterThan(String value) {
            addCriterion("regcodeimg >", value, "regcodeimg");
            return (Criteria) this;
        }

        public Criteria andRegcodeimgGreaterThanOrEqualTo(String value) {
            addCriterion("regcodeimg >=", value, "regcodeimg");
            return (Criteria) this;
        }

        public Criteria andRegcodeimgLessThan(String value) {
            addCriterion("regcodeimg <", value, "regcodeimg");
            return (Criteria) this;
        }

        public Criteria andRegcodeimgLessThanOrEqualTo(String value) {
            addCriterion("regcodeimg <=", value, "regcodeimg");
            return (Criteria) this;
        }

        public Criteria andRegcodeimgLike(String value) {
            addCriterion("regcodeimg like", value, "regcodeimg");
            return (Criteria) this;
        }

        public Criteria andRegcodeimgNotLike(String value) {
            addCriterion("regcodeimg not like", value, "regcodeimg");
            return (Criteria) this;
        }

        public Criteria andRegcodeimgIn(List<String> values) {
            addCriterion("regcodeimg in", values, "regcodeimg");
            return (Criteria) this;
        }

        public Criteria andRegcodeimgNotIn(List<String> values) {
            addCriterion("regcodeimg not in", values, "regcodeimg");
            return (Criteria) this;
        }

        public Criteria andRegcodeimgBetween(String value1, String value2) {
            addCriterion("regcodeimg between", value1, value2, "regcodeimg");
            return (Criteria) this;
        }

        public Criteria andRegcodeimgNotBetween(String value1, String value2) {
            addCriterion("regcodeimg not between", value1, value2, "regcodeimg");
            return (Criteria) this;
        }

        public Criteria andLogoIsNull() {
            addCriterion("logo is null");
            return (Criteria) this;
        }

        public Criteria andLogoIsNotNull() {
            addCriterion("logo is not null");
            return (Criteria) this;
        }

        public Criteria andLogoEqualTo(String value) {
            addCriterion("logo =", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotEqualTo(String value) {
            addCriterion("logo <>", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThan(String value) {
            addCriterion("logo >", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThanOrEqualTo(String value) {
            addCriterion("logo >=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThan(String value) {
            addCriterion("logo <", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThanOrEqualTo(String value) {
            addCriterion("logo <=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLike(String value) {
            addCriterion("logo like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotLike(String value) {
            addCriterion("logo not like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoIn(List<String> values) {
            addCriterion("logo in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotIn(List<String> values) {
            addCriterion("logo not in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoBetween(String value1, String value2) {
            addCriterion("logo between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotBetween(String value1, String value2) {
            addCriterion("logo not between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
        
        public Criteria andSql(String value) {
            addCriterion(value);
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sme_svorg
     *
     * @mbggenerated do_not_delete_during_merge Thu Mar 17 11:21:56 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sme_svorg
     *
     * @mbggenerated Thu Mar 17 11:21:56 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}