package com.gsccs.sme.plat.corp.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.gsccs.sme.api.domain.corp.CorpWater;
import com.gsccs.sme.plat.corp.model.CorpWaterExample;

public interface CorpWaterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_water
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    int countByExample(CorpWaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_water
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    int deleteByExample(CorpWaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_water
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_water
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    int insert(CorpWater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_water
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    int insertSelective(CorpWater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_water
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    List<CorpWater> selectByExample(CorpWaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_water
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    CorpWater selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_water
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") CorpWater record, @Param("example") CorpWaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_water
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    int updateByExample(@Param("record") CorpWater record, @Param("example") CorpWaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_water
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    int updateByPrimaryKeySelective(CorpWater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_water
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    int updateByPrimaryKey(CorpWater record);
}