package com.gsccs.sme.plat.corp.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.gsccs.sme.api.domain.corp.CorpRun;
import com.gsccs.sme.plat.corp.model.CorpRunExample;

public interface CorpRunMapper {
	int countByExample(CorpRunExample example);

	int deleteByExample(CorpRunExample example);

	int deleteByPrimaryKey(Long id);

	int insert(CorpRun record);

	int insertSelective(CorpRun record);

	List<CorpRun> selectByExample(CorpRunExample example);

	CorpRun selectByPrimaryKey(Long id);

	int updateByExampleSelective(@Param("record") CorpRun record,
			@Param("example") CorpRunExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sme_corp_run
	 * 
	 * @mbggenerated Tue Jul 26 15:20:16 CST 2016
	 */
	int updateByExample(@Param("record") CorpRun record,
			@Param("example") CorpRunExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sme_corp_run
	 * 
	 * @mbggenerated Tue Jul 26 15:20:16 CST 2016
	 */
	int updateByPrimaryKeySelective(CorpRun record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sme_corp_run
	 * 
	 * @mbggenerated Tue Jul 26 15:20:16 CST 2016
	 */
	int updateByPrimaryKey(CorpRun record);
}