package com.gsccs.sme.plat.corp.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.gsccs.sme.api.domain.corp.CorpTech;
import com.gsccs.sme.plat.corp.model.CorpTechExample;

public interface CorpTechMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_tech
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    int countByExample(CorpTechExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_tech
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    int deleteByExample(CorpTechExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_tech
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_tech
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    int insert(CorpTech record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_tech
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    int insertSelective(CorpTech record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_tech
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    List<CorpTech> selectByExample(CorpTechExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_tech
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    CorpTech selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_tech
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") CorpTech record, @Param("example") CorpTechExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_tech
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    int updateByExample(@Param("record") CorpTech record, @Param("example") CorpTechExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_tech
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    int updateByPrimaryKeySelective(CorpTech record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sme_corp_tech
     *
     * @mbggenerated Tue Jul 26 11:09:03 CST 2016
     */
    int updateByPrimaryKey(CorpTech record);
}