package com.gsccs.sme.plat.shop.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.gsccs.sme.plat.bass.BaseExample;

public class OrderitemExample extends BaseExample {
	protected String orderByClause;
	protected boolean distinct;
	protected List<Criteria> oredCriteria;

	public OrderitemExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_item
	 * 
	 * @mbggenerated Mon Apr 04 10:46:39 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_item
	 * 
	 * @mbggenerated Mon Apr 04 10:46:39 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_item
	 * 
	 * @mbggenerated Mon Apr 04 10:46:39 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_item
	 * 
	 * @mbggenerated Mon Apr 04 10:46:39 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_item
	 * 
	 * @mbggenerated Mon Apr 04 10:46:39 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_item
	 * 
	 * @mbggenerated Mon Apr 04 10:46:39 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_item
	 * 
	 * @mbggenerated Mon Apr 04 10:46:39 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_item
	 * 
	 * @mbggenerated Mon Apr 04 10:46:39 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_item
	 * 
	 * @mbggenerated Mon Apr 04 10:46:39 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_item
	 * 
	 * @mbggenerated Mon Apr 04 10:46:39 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table shop_order_item
	 * 
	 * @mbggenerated Mon Apr 04 10:46:39 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andOrderidIsNull() {
			addCriterion("orderid is null");
			return (Criteria) this;
		}

		public Criteria andOrderidIsNotNull() {
			addCriterion("orderid is not null");
			return (Criteria) this;
		}

		public Criteria andOrderidEqualTo(Long value) {
			addCriterion("orderid =", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidNotEqualTo(Long value) {
			addCriterion("orderid <>", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidIn(List<String> values) {
			addCriterion("orderid in", values, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidNotIn(List<String> values) {
			addCriterion("orderid not in", values, "orderid");
			return (Criteria) this;
		}

		public Criteria andProductidIsNull() {
			addCriterion("productid is null");
			return (Criteria) this;
		}

		public Criteria andProductidIsNotNull() {
			addCriterion("productid is not null");
			return (Criteria) this;
		}

		public Criteria andProductidEqualTo(Long value) {
			addCriterion("productid =", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidNotEqualTo(Long value) {
			addCriterion("productid <>", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidIn(List<Long> values) {
			addCriterion("productid in", values, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidNotIn(List<Long> values) {
			addCriterion("productid not in", values, "productid");
			return (Criteria) this;
		}

		public Criteria andGoodsidIsNull() {
			addCriterion("goodsid is null");
			return (Criteria) this;
		}

		public Criteria andGoodsidIsNotNull() {
			addCriterion("goodsid is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsidEqualTo(Long value) {
			addCriterion("goodsid =", value, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidNotEqualTo(Long value) {
			addCriterion("goodsid <>", value, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidIn(List<Long> values) {
			addCriterion("goodsid in", values, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidNotIn(List<Long> values) {
			addCriterion("goodsid not in", values, "goodsid");
			return (Criteria) this;
		}

		public Criteria andNumIsNull() {
			addCriterion("num is null");
			return (Criteria) this;
		}

		public Criteria andNumIsNotNull() {
			addCriterion("num is not null");
			return (Criteria) this;
		}

		public Criteria andNumEqualTo(Integer value) {
			addCriterion("num =", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotEqualTo(Integer value) {
			addCriterion("num <>", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumGreaterThan(Integer value) {
			addCriterion("num >", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("num >=", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumLessThan(Integer value) {
			addCriterion("num <", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumLessThanOrEqualTo(Integer value) {
			addCriterion("num <=", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumBetween(Integer value1, Integer value2) {
			addCriterion("num between", value1, value2, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotBetween(Integer value1, Integer value2) {
			addCriterion("num not between", value1, value2, "num");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(BigDecimal value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(BigDecimal value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(BigDecimal value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(BigDecimal value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<BigDecimal> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<BigDecimal> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andTotalfeeIsNull() {
			addCriterion("totalfee is null");
			return (Criteria) this;
		}

		public Criteria andTotalfeeIsNotNull() {
			addCriterion("totalfee is not null");
			return (Criteria) this;
		}

		public Criteria andTotalfeeEqualTo(Long value) {
			addCriterion("totalfee =", value, "totalfee");
			return (Criteria) this;
		}

		public Criteria andTotalfeeNotEqualTo(Long value) {
			addCriterion("totalfee <>", value, "totalfee");
			return (Criteria) this;
		}

		public Criteria andTotalfeeGreaterThan(Long value) {
			addCriterion("totalfee >", value, "totalfee");
			return (Criteria) this;
		}

		public Criteria andTotalfeeGreaterThanOrEqualTo(Long value) {
			addCriterion("totalfee >=", value, "totalfee");
			return (Criteria) this;
		}

		public Criteria andTotalfeeLessThan(Long value) {
			addCriterion("totalfee <", value, "totalfee");
			return (Criteria) this;
		}

		public Criteria andTotalfeeLessThanOrEqualTo(Long value) {
			addCriterion("totalfee <=", value, "totalfee");
			return (Criteria) this;
		}

		public Criteria andTotalfeeIn(List<Long> values) {
			addCriterion("totalfee in", values, "totalfee");
			return (Criteria) this;
		}

		public Criteria andTotalfeeNotIn(List<Long> values) {
			addCriterion("totalfee not in", values, "totalfee");
			return (Criteria) this;
		}

		public Criteria andTotalfeeBetween(Long value1, Long value2) {
			addCriterion("totalfee between", value1, value2, "totalfee");
			return (Criteria) this;
		}

		public Criteria andTotalfeeNotBetween(Long value1, Long value2) {
			addCriterion("totalfee not between", value1, value2, "totalfee");
			return (Criteria) this;
		}

		public Criteria andBuyeridIsNull() {
			addCriterion("buyerid is null");
			return (Criteria) this;
		}

		public Criteria andBuyeridIsNotNull() {
			addCriterion("buyerid is not null");
			return (Criteria) this;
		}

		public Criteria andBuyeridEqualTo(String value) {
			addCriterion("buyerid =", value, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyeridNotEqualTo(String value) {
			addCriterion("buyerid <>", value, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyeridGreaterThan(String value) {
			addCriterion("buyerid >", value, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyeridGreaterThanOrEqualTo(String value) {
			addCriterion("buyerid >=", value, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyeridLessThan(String value) {
			addCriterion("buyerid <", value, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyeridLessThanOrEqualTo(String value) {
			addCriterion("buyerid <=", value, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyeridLike(String value) {
			addCriterion("buyerid like", value, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyeridNotLike(String value) {
			addCriterion("buyerid not like", value, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyeridIn(List<String> values) {
			addCriterion("buyerid in", values, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyeridNotIn(List<String> values) {
			addCriterion("buyerid not in", values, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyeridBetween(String value1, String value2) {
			addCriterion("buyerid between", value1, value2, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyeridNotBetween(String value1, String value2) {
			addCriterion("buyerid not between", value1, value2, "buyerid");
			return (Criteria) this;
		}

		public Criteria andSelleridIsNull() {
			addCriterion("sellerid is null");
			return (Criteria) this;
		}

		public Criteria andSelleridIsNotNull() {
			addCriterion("sellerid is not null");
			return (Criteria) this;
		}

		public Criteria andSelleridEqualTo(String value) {
			addCriterion("sellerid =", value, "sellerid");
			return (Criteria) this;
		}

		public Criteria andSelleridNotEqualTo(String value) {
			addCriterion("sellerid <>", value, "sellerid");
			return (Criteria) this;
		}

		public Criteria andSelleridGreaterThan(String value) {
			addCriterion("sellerid >", value, "sellerid");
			return (Criteria) this;
		}

		public Criteria andSelleridGreaterThanOrEqualTo(String value) {
			addCriterion("sellerid >=", value, "sellerid");
			return (Criteria) this;
		}

		public Criteria andSelleridLessThan(String value) {
			addCriterion("sellerid <", value, "sellerid");
			return (Criteria) this;
		}

		public Criteria andSelleridLessThanOrEqualTo(String value) {
			addCriterion("sellerid <=", value, "sellerid");
			return (Criteria) this;
		}

		public Criteria andSelleridLike(String value) {
			addCriterion("sellerid like", value, "sellerid");
			return (Criteria) this;
		}

		public Criteria andSelleridNotLike(String value) {
			addCriterion("sellerid not like", value, "sellerid");
			return (Criteria) this;
		}

		public Criteria andSelleridIn(List<String> values) {
			addCriterion("sellerid in", values, "sellerid");
			return (Criteria) this;
		}

		public Criteria andSelleridNotIn(List<String> values) {
			addCriterion("sellerid not in", values, "sellerid");
			return (Criteria) this;
		}

		public Criteria andSelleridBetween(String value1, String value2) {
			addCriterion("sellerid between", value1, value2, "sellerid");
			return (Criteria) this;
		}

		public Criteria andSelleridNotBetween(String value1, String value2) {
			addCriterion("sellerid not between", value1, value2, "sellerid");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNull() {
			addCriterion("addtime is null");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNotNull() {
			addCriterion("addtime is not null");
			return (Criteria) this;
		}

		public Criteria andAddtimeEqualTo(Date value) {
			addCriterion("addtime =", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotEqualTo(Date value) {
			addCriterion("addtime <>", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThan(Date value) {
			addCriterion("addtime >", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("addtime >=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThan(Date value) {
			addCriterion("addtime <", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThanOrEqualTo(Date value) {
			addCriterion("addtime <=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeIn(List<Date> values) {
			addCriterion("addtime in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotIn(List<Date> values) {
			addCriterion("addtime not in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeBetween(Date value1, Date value2) {
			addCriterion("addtime between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotBetween(Date value1, Date value2) {
			addCriterion("addtime not between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andGoodstitleIsNull() {
			addCriterion("goodstitle is null");
			return (Criteria) this;
		}

		public Criteria andGoodstitleIsNotNull() {
			addCriterion("goodstitle is not null");
			return (Criteria) this;
		}

		public Criteria andGoodstitleEqualTo(String value) {
			addCriterion("goodstitle =", value, "goodstitle");
			return (Criteria) this;
		}

		public Criteria andGoodstitleNotEqualTo(String value) {
			addCriterion("goodstitle <>", value, "goodstitle");
			return (Criteria) this;
		}

		public Criteria andGoodstitleGreaterThan(String value) {
			addCriterion("goodstitle >", value, "goodstitle");
			return (Criteria) this;
		}

		public Criteria andGoodstitleGreaterThanOrEqualTo(String value) {
			addCriterion("goodstitle >=", value, "goodstitle");
			return (Criteria) this;
		}

		public Criteria andGoodstitleLessThan(String value) {
			addCriterion("goodstitle <", value, "goodstitle");
			return (Criteria) this;
		}

		public Criteria andGoodstitleLessThanOrEqualTo(String value) {
			addCriterion("goodstitle <=", value, "goodstitle");
			return (Criteria) this;
		}

		public Criteria andGoodstitleLike(String value) {
			addCriterion("goodstitle like", value, "goodstitle");
			return (Criteria) this;
		}

		public Criteria andGoodstitleNotLike(String value) {
			addCriterion("goodstitle not like", value, "goodstitle");
			return (Criteria) this;
		}

		public Criteria andGoodstitleIn(List<String> values) {
			addCriterion("goodstitle in", values, "goodstitle");
			return (Criteria) this;
		}

		public Criteria andGoodstitleNotIn(List<String> values) {
			addCriterion("goodstitle not in", values, "goodstitle");
			return (Criteria) this;
		}

		public Criteria andGoodstitleBetween(String value1, String value2) {
			addCriterion("goodstitle between", value1, value2, "goodstitle");
			return (Criteria) this;
		}

		public Criteria andGoodstitleNotBetween(String value1, String value2) {
			addCriterion("goodstitle not between", value1, value2, "goodstitle");
			return (Criteria) this;
		}

		public Criteria andGoodsurlIsNull() {
			addCriterion("goodsurl is null");
			return (Criteria) this;
		}

		public Criteria andGoodsurlIsNotNull() {
			addCriterion("goodsurl is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsurlEqualTo(String value) {
			addCriterion("goodsurl =", value, "goodsurl");
			return (Criteria) this;
		}

		public Criteria andGoodsurlNotEqualTo(String value) {
			addCriterion("goodsurl <>", value, "goodsurl");
			return (Criteria) this;
		}

		public Criteria andGoodsurlGreaterThan(String value) {
			addCriterion("goodsurl >", value, "goodsurl");
			return (Criteria) this;
		}

		public Criteria andGoodsurlGreaterThanOrEqualTo(String value) {
			addCriterion("goodsurl >=", value, "goodsurl");
			return (Criteria) this;
		}

		public Criteria andGoodsurlLessThan(String value) {
			addCriterion("goodsurl <", value, "goodsurl");
			return (Criteria) this;
		}

		public Criteria andGoodsurlLessThanOrEqualTo(String value) {
			addCriterion("goodsurl <=", value, "goodsurl");
			return (Criteria) this;
		}

		public Criteria andGoodsurlLike(String value) {
			addCriterion("goodsurl like", value, "goodsurl");
			return (Criteria) this;
		}

		public Criteria andGoodsurlNotLike(String value) {
			addCriterion("goodsurl not like", value, "goodsurl");
			return (Criteria) this;
		}

		public Criteria andGoodsurlIn(List<String> values) {
			addCriterion("goodsurl in", values, "goodsurl");
			return (Criteria) this;
		}

		public Criteria andGoodsurlNotIn(List<String> values) {
			addCriterion("goodsurl not in", values, "goodsurl");
			return (Criteria) this;
		}

		public Criteria andGoodsurlBetween(String value1, String value2) {
			addCriterion("goodsurl between", value1, value2, "goodsurl");
			return (Criteria) this;
		}

		public Criteria andGoodsurlNotBetween(String value1, String value2) {
			addCriterion("goodsurl not between", value1, value2, "goodsurl");
			return (Criteria) this;
		}

		public Criteria andSpecstrIsNull() {
			addCriterion("specstr is null");
			return (Criteria) this;
		}

		public Criteria andSpecstrIsNotNull() {
			addCriterion("specstr is not null");
			return (Criteria) this;
		}

		public Criteria andSpecstrEqualTo(String value) {
			addCriterion("specstr =", value, "specstr");
			return (Criteria) this;
		}

		public Criteria andSpecstrNotEqualTo(String value) {
			addCriterion("specstr <>", value, "specstr");
			return (Criteria) this;
		}

		public Criteria andSpecstrGreaterThan(String value) {
			addCriterion("specstr >", value, "specstr");
			return (Criteria) this;
		}

		public Criteria andSpecstrGreaterThanOrEqualTo(String value) {
			addCriterion("specstr >=", value, "specstr");
			return (Criteria) this;
		}

		public Criteria andSpecstrLessThan(String value) {
			addCriterion("specstr <", value, "specstr");
			return (Criteria) this;
		}

		public Criteria andSpecstrLessThanOrEqualTo(String value) {
			addCriterion("specstr <=", value, "specstr");
			return (Criteria) this;
		}

		public Criteria andSpecstrLike(String value) {
			addCriterion("specstr like", value, "specstr");
			return (Criteria) this;
		}

		public Criteria andSpecstrNotLike(String value) {
			addCriterion("specstr not like", value, "specstr");
			return (Criteria) this;
		}

		public Criteria andSpecstrIn(List<String> values) {
			addCriterion("specstr in", values, "specstr");
			return (Criteria) this;
		}

		public Criteria andSpecstrNotIn(List<String> values) {
			addCriterion("specstr not in", values, "specstr");
			return (Criteria) this;
		}

		public Criteria andSpecstrBetween(String value1, String value2) {
			addCriterion("specstr between", value1, value2, "specstr");
			return (Criteria) this;
		}

		public Criteria andSpecstrNotBetween(String value1, String value2) {
			addCriterion("specstr not between", value1, value2, "specstr");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table shop_order_item
	 * 
	 * @mbggenerated do_not_delete_during_merge Mon Apr 04 10:46:39 CST 2016
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table shop_order_item
	 * 
	 * @mbggenerated Mon Apr 04 10:46:39 CST 2016
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}