package com.gsccs.sme.plat.shop.model;

import java.util.Date;

public class ProductImgT {
	
    private Long id;
    private Date modified;
    private Long position;
    private Long productid;
    private String url;
    private Date created;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_product_img.modified
     *
     * @param modified the value for shop_product_img.modified
     *
     * @mbggenerated Sat Mar 12 19:19:50 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_product_img.position
     *
     * @return the value of shop_product_img.position
     *
     * @mbggenerated Sat Mar 12 19:19:50 CST 2016
     */
    public Long getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_product_img.position
     *
     * @param position the value for shop_product_img.position
     *
     * @mbggenerated Sat Mar 12 19:19:50 CST 2016
     */
    public void setPosition(Long position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_product_img.productId
     *
     * @return the value of shop_product_img.productId
     *
     * @mbggenerated Sat Mar 12 19:19:50 CST 2016
     */
    public Long getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_product_img.productId
     *
     * @param productid the value for shop_product_img.productId
     *
     * @mbggenerated Sat Mar 12 19:19:50 CST 2016
     */
    public void setProductid(Long productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_product_img.url
     *
     * @return the value of shop_product_img.url
     *
     * @mbggenerated Sat Mar 12 19:19:50 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_product_img.url
     *
     * @param url the value for shop_product_img.url
     *
     * @mbggenerated Sat Mar 12 19:19:50 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_product_img.created
     *
     * @return the value of shop_product_img.created
     *
     * @mbggenerated Sat Mar 12 19:19:50 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_product_img.created
     *
     * @param created the value for shop_product_img.created
     *
     * @mbggenerated Sat Mar 12 19:19:50 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}